### PR TITLE
Fix: Correct flood + transmission rate units

### LINKED ISSUE #1021: [Bug] Flood widget download and upload use wrong unit
### Description

The Flood widget upload and download rates are incorrect:
- Value is in B/s
- Unit is b/s

### Steps to reproduce

Screenshot 2023-02-19 at 10 28 11

### homepage version

v0.6.7 (f8a0c69, Feb 7, 2023)

### Installation method

Docker

### Configuration

_No response_

### Container Logs

_No response_

### Browser Logs

_No response_

### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

### PR DESCRIPTION
**Pull request by danroc**
## Proposed change

Convert Flood download and upload rates from B/s to b/s

Closes #1021

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [ ] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Please see my commit, which I think is what this should be:
Screenshot 2023-02-19 at 7 14 52 AM

Here's what I was seeing with yours:
Screenshot 2023-02-19 at 7 13 54 AM

**Comment by danroc** [comment]
Indeed, I was divided between fixing the value or the unit. In this case should we also use byterate in the Transmission widget?

**Comment by shamoon** [comment]
Ah, good point
Screenshot 2023-02-19 at 7 43 58 AM

**Comment by shamoon** [comment]
Screenshot 2023-02-19 at 7 45 39 AM

**Comment by danroc** [comment]
Thanks!

**Pull request merged**
