### PR TITLE
Feature: tabbed layouts

### PR DESCRIPTION
**Pull request by denispapec**
## Proposed change

This pull request implements tabs when `tab:`  is defined in the layout configuration for at least single service/bookmark group (as suggested in https://github.com/benphelps/homepage/discussions/1316#discussioncomment-6165188).

Tabs will sort based on the order in the layout block. 
If there are no tabs defined, all services/bookmarks groups will be shown. 
If the group doesn't have a tab definition, it will be shown on every tab.
Every tab can be accessed directly by visiting Homepage URL with `#Group name` at the end of the URL.

I had a bit of trouble making a design of the tabs to look similar to the rest of the UI (using any colour), but I'm no designer so any suggestions or CSS changes are welcome. 

https://github.com/benphelps/homepage/assets/5442891/ffcacab6-9b49-4296-affe-54440eccc82b

<details>
<summary>Layout example</summary>

```yaml
  Developer Bookmark on First Tab:
    tab: First

  My First Group:
    tab: First
    style: row
    columns: 4

  My Second Group:
    tab: Second
    style: row
    columns: 4

  My Third Group:
    tab: Third
    style: row
    columns: 4

  My Forth Group:
    tab: Forth
    style: row
    columns: 4

  My Group on every Tab:
    style: row
    columns: 4

  Entertainment Bookmark on every Tab:
    style: row
```
</details>

Closes #1316 

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [x] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Cool, looking forward to taking a look at your PR. Yes I do think the visual design will need some work :)

**Comment by denispapec** [comment]
Haha, although it look a bit better when there is background image (so it has opacity and blur): 
P.S. Graphs is active tab (slightly darker than rest), and hover is lighter than the rest.
image

**Comment by shamoon** [comment]
Screenshot 2023-09-14 at 12 37 16 AM
Screenshot 2023-09-14 at 12 36 17 AM

**Comment by shamoon** [comment]
Works great overall

**Comment by benphelps** [comment]
Works well, I like it.  Will the docker discovery need any modification?

**Comment by shamoon** [comment]
I don't think its an issue because its at the layout level (I tested it too didnt notice anything)

**Comment by denispapec** [comment]
@shamoon Nice, I really like style improvements!

**Comment by GAntoine** [comment]
this is huge, thank you @denispapec!!

**Comment by serverless83** [comment]
Great addition, thank you!

**Pull request merged**
