### PR TITLE
feature: add homebridge widget

### PR DESCRIPTION
**Pull request by Fernando-Neira**
Simple homebridge widget,

How to use:

```javascript
    - Homebridge:
        icon: homebridge.png
        container: homebridge
        service: homebridge
        href: http://your-ip-address:8581
        description:
        widget:
            type: homebridge
            url: http://your-ip-address:8581
            username: your-username
            password: your-password
```

Preview:

image

If you dont have child bridges:

image

### CODE REVIEW

**Comment by shamoon** [comment]
Nice, it works! =)

Couple thoughts:

1. The API (swagger) allows for basic auth, so you dont actually need the whole proxy here...
2. It could be more useful than the current items to show things like # of child bridges which many use (myself included). We could make it only show if n > 0? Only problem is its another API call. `/api/status/homebridge/child-bridges`. I'll have a think
3. Technically, this requires Config UI X (thats where the API comes from). Most people, especially at this point, have this, but its not actually required. We can note this in the docs.

Let me know your thoughts on # 2, I can help out with # 1 if you'd like

**Comment by shamoon** [comment]
Sorry may have spoken too soon, 1 sec!

**Comment by Fernando-Neira** [comment]
@shamoon  update the preview image, and add child_bridges api support :)

**Comment by shamoon** [comment]
Love it! I'll take a look later when I have some real time, thanks for the pr!

**Comment by shamoon** [comment]
Just some minor stuff, works great though =)

I will take a final look at it tonight, thanks again

**Comment by shamoon** [comment]
Nice work!

**Pull request merged**
