### PR TITLE
Feature: Omada widget

### LINKED ISSUE #202: [Feature Request] TPLink Omada Widget
TPLink Omada is a becoming popular home networking hardware (similar to Ubiquiti's UniFi system) and they have a pretty extensive API for retrieving information on the network status. Would be awesome to have this added as a widget. 

Here is a link to their published API for their current v5.0+ controllers: https://static-community.tp-link.com/attach/8/2/2022/78d3f067ac0c491d931426e040188632.zip

### PR DESCRIPTION
**Pull request by shamoon**
Supersedes #674 

Obviously this is working for me locally (with all 3 versions of API) but I dont have any actual devices so would be good if someone can test and report.

@Oupsman sorry to close your PR but needed to squash your commits [for reasons discussed](https://github.com/benphelps/homepage/pull/674#issuecomment-1349262127) =) and because of the way you added commits they couldn't be squashed in your branch. Also, even thought this required some changes, still appreciate your effort!

Screen Shot 2022-12-21 at 12 50 00 PM
Screen Shot 2022-12-21 at 12 27 10 PM
Screen Shot 2022-12-21 at 12 21 38 PM

Closes #202 

```yaml
widget:
    type: omada
    url: https://localhost:8043
    username: username
    password: password
    site: Default
```

### CODE REVIEW

**Comment by shamoon** [comment]
> Well, I really would have preferred to work with you on this one, so I could learn and improve myself.
> 
> Frankly, I am _REALLY_ unhappy of the way you handled this.

Well sorry. To be clear, I did still use your code, it was helpful! You can look at my commits and see what I did, basically moved things around and cleaned them up.

im not sure what you would have preferred? I’d be happy to try and answer your questions about it if that helps?

**Comment by Oupsman** [comment]
Well I have three goals : 
- add an omada widget
- learn JS as a server language
- learn how to contribute to an opensource project with github.

**Comment by Oupsman** [comment]
The point 4 triggers warnings in my IDE (WebStorm) because the contentType variable is never used. And I don't like warnings if there is another way. So I've changed the line to get an array and use only the elements I need. Which is a way of writing code I prefer :) 

But I agree with you, I should have wrote the code using the same coding style that I saw in the other widgets and ignore the warnings.

**Comment by shamoon** [comment]
> Well I have three goals :
> 
> * add an omada widget
> * learn JS as a server language
> * learn how to contribute to an opensource project with github.

I appreciate that. Sometimes if the code changes are small / few it makes sense to add comments. The overall logic of your code was sound (again, the overall logic is mostly preserved) but syntax-wise etc there was a lot to change, and as you are still learning I didnt think it made sense to ask all of that of you.

Im sure there are many ways to collaborate on github or in general. But in general, as I often see, when a maintainer adds changes to your code all of those changes are of course visible to you so you can look at that as a way to learn. That's sort of the purpose of 'maintainers' or of course the owner a project.

Again, I will emphasize your code is still there, your name is in the github history and your contribution is still noted and appreciated. I hope the explanation above helps too.

**Comment by shamoon** [comment]
> The point 4 triggers warnings in my IDE (WebStorm) because the contentType variable is never used. And I don't like warnings if there is another way. So I've changed the line to get an array and use only the elements I need. Which is a way of writing code I prefer :)

Yes this comes up frequently in the homepage codebase, there are pros/cons but itsis something used many times in this project. That's also why the `eslint-disable-next-line no-unused-vars` https://github.com/benphelps/homepage/blob/952305492cf28fe523a6afac121bbfdd2d320608/src/widgets/omada/proxy.js#L226

Using an object for destructuring as opposed to an array solves this issue because you can explicitly choose which return values to use, but of course that would a much wider change to the codebase.

**Comment by Oupsman** [comment]
> Im sure there are many ways to collaborate on github or in general. But in general, as I often see, when a maintainer adds changes to your code all of those changes are of course visible to you so you can look at that as a way to learn. That's sort of the purpose of 'maintainers' or of course the owner a project.

Oh, that's not what I'm trying to say : I made a mess with Git by merging the code from the upstream and that prevented me from squashing the commits before pushing to Github. 

I'm more an OPS guy (system engineer) and used to collaborate using SVN. 

So forking, merging are pretty new to me (I'm using a private gitlab instance for my code that I'm working on alone ... ) and I would like to learn how to use Github in an efficient way. Hell, before you told me to squash commits, I didn't even know that this feature existed.

**Comment by shamoon** [comment]
> So forking, merging are pretty new to me (I'm using a private gitlab instance for my code that I'm working on alone ... ) and I would like to learn how to use Github in an efficient way. Hell, before you told me to squash commits, I didn't even know that this feature existed.

Ah, understood. Yes you cant "squash" merge commits but you can accomplish the same thing by creating a new branch and squashing the changes into that new branch, which is why this is a separate PR.

**Comment by Oupsman** [comment]
BTW, I tried the widget, it works. I tried to pass wrong values to the widget, it triggers meaningful error :)

**Comment by shamoon** [comment]
> BTW, I tried the widget, it works. I tried to pass wrong values to the widget, it triggers meaningful error :)

Thank you, and again I will keep in mind all that you've said.

**Comment by Oupsman** [comment]
> > So forking, merging are pretty new to me (I'm using a private gitlab instance for my code that I'm working on alone ... ) and I would like to learn how to use Github in an efficient way. Hell, before you told me to squash commits, I didn't even know that this feature existed.
> 
> Ah, understood. Yes you cant "squash" merge commits but you can accomplish the same thing by creating a new branch and squashing the changes into that new branch, which is why this is a separate PR.

So, if I understand correctly, I should had created a new branch in my fork, merged my branch with the main branch of my fork and created the PR ?

**Comment by shamoon** [comment]
> So, if I understand correctly, I should had created a new branch in my fork, merged my branch with the main branch of my fork and created the PR ?

Yes that would have allowed you to "squash" (btw this usually goes along with a "force-push") those commits to:

1. Effectively "undo" any changes. For example if you make a change, undo it and then "squash" those commits the new commit history wont contain those at all. In your case I did this the IDE files, for example.
2. Edit the commit messages, e.g. in this case removing the curse words.
3. Simplify the commit history, this is not really a necessary thing of course but most people prefer to not have too many 'extraneous' commits.

The thing to know about "squashing" commits (again squashing and then force-pushing) is that theyre effectively altering the git history so anyone using the same branch is suddenly on the 'wrong' one, if that makes sense. Its fine to use in a branch that's only for a PR (and will be deleted after) but you probably wouldn't want to force-push to a `main` branch or something like that unless every single person contributing was aware of that plan.

**Pull request merged**
