### PR TITLE
Omada Widget

### PR DESCRIPTION
**Pull request by Oupsman**
Pull request for Omada Widget. 

Configuration of the widget is as such : 

        widget:
          type: omada
          url: https://locahost:8043
          username: homepage
          password: password
          site: Maison
          legacy: true for controller v3, false for controller v4 and +

### CODE REVIEW

**Comment by shamoon** [comment]
You got it, nice!

In order to test this, since I dont have the hardware, can you copy and paste some output from the API? Ideally we could get that for older vs newer versions.

Thanks

**Comment by Oupsman** [comment]
[responses.txt](https://github.com/benphelps/homepage/files/10178206/responses.txt)

**Review by shamoon — CHANGES_REQUESTED** [review]
Thanks again for the PR.

Ok so there are some small issues with the code but before I get into those there are some big ones before this can be considered for commit:

1. The new API doesnt work? If you cant test it (me neither) we need to get either someone to test or example API output at the very least. It doesnt make sense to merge without that...
2. Please dont just duplicate the entire logic in `legacy` vs not, they need to be combined or separated into two widgets if theyre truly totally different.

**Comment by Oupsman** [comment]
1/ In the responses.txt file, you'll see samples for both modern and legacy controllers : I've setup a modern controller on my laptop for me to test. 

2/ I'll change my code, I agree with you, it's not ideal.

**Comment by Oupsman** [comment]
Code is unstable.

**Pull request closed without merging**
