### PR TITLE
Add HDHomeRun widget

### PR DESCRIPTION
**Pull request by donslice**
- Tracking Channels, and HD Channels
- Condensed API Calls into 1, per request in [earlier pr](https://github.com/benphelps/homepage/pull/481)

firefox_XuWsRf9ia8

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Thanks for the changes.

I can at least verify this PR with the [sample data](https://github.com/benphelps/homepage/pull/481#issuecomment-1303794380) provided, if @benphelps youre good with that

**Comment by rursache** [comment]
@donslice any chance you can do this for tvheadend too? thanks

**Comment by JazzFisch** [comment]
@donslice can you please resolve the merge conflicts?  Thanks.

**Comment by shamoon** [comment]
resolved =)

**Review by benphelps — APPROVED** [review]
Looks good.

**Comment by shamoon** [comment]
Cheers thanks!

**Pull request merged**
