### PR TITLE
Added PiAlert widget [WIP]

### PR DESCRIPTION
**Pull request by thegabriele97**
## Proposed change

This PR introduces the new PiAlert widget that pulls stats from PiAlert's APi (https://github.com/jokob-sk/Pi.Alert).

image

The user will be able to add the widget to the services.yaml file using the following configuration:

```yaml
widget:
    type: pialert
    url: http://ip:port
```

The PiAlert's API are not documented, I am using as endpoint /php/server/devices.php?action=getDevicesTotals, that returns the following response:

```js
[30,22,0,0,0,0]
```

It is an array where each item corresponds respectively to AllDevices, Connected, Favorites, NewDevices, DownAlerts, Archived.

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/101
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thank you but we only accept service widget PRs based on feature requests with interest (currently arbitrarily designated as 5 "up-votes") from the community...

Feel free to open FR for this

See https://gethomepage.dev/en/more/development/#service-widget-guidelines

**Comment by thegabriele97** [comment]
> Thank you but we only accept service widget PRs based on feature requests with interest (currently arbitrarily designated as 5 "up-votes") from the community...
> 
> Feel free to open FR for this
> 
> See https://gethomepage.dev/en/more/development/#service-widget-guidelines

Hi! I opened a FR and it received 5 up-votes. Any chance to reopen this PR? Thank you

**Comment by shamoon** [comment]
This works fine in my testing, please see the small changes. Any other reason this was marked as a draft?

**Comment by shamoon** [comment]
Ps. Please create a documentation PR as noted above

**Comment by thegabriele97** [comment]
> This works fine in my testing, please see the small changes. Any other reason this was marked as a draft?

Thank you. It was marked as draft because I needed to finish a few things (as you did, thank you) and I still need to create a PR in the documentation repo. I will do ASAP

**Comment by thegabriele97** [comment]
Done!

**Comment by shamoon** [comment]
Great thanks

**Pull request merged**
