### PR TITLE
Feature: PhotoPrism widget

### PR DESCRIPTION
**Pull request by geckoflume**
# Overview
Since I was not able to find a [PhotoPrism](https://photoprism.app/) widget, I made one! PhotoPrism is similar to Immich (widget added in v0.6.4), a user- and privacy-friendly solution to keep your pictures organized and accessible. It is an AI-Powered Photos App that makes use of the latest technologies to tag and find pictures automatically.

# Image
image

# How to use
```yaml
widget:
  type: photoprism
  url: http://photoprism.host.or.ip:port
  username: admin
  password: password
```
Since there is no way of adding limited users, nor API key (yet?), admin user must be used.

# Example API calls
See [https://docs.photoprism.app/developer-guide/api/](https://docs.photoprism.app/developer-guide/api/) for details, but this widget uses the following:
## [POST /api/v1/session](https://pkg.go.dev/github.com/photoprism/photoprism/internal/api?utm_source=godoc#CreateSession)
```json
{
    "config": {
        "mode": "user",
        "name": "PhotoPrism",
        "about": "PhotoPrism® CE",
        "edition": "ce",
        "version": "230113-e58fee0fb-Linux-AMD64",
        "copyright": "(c) 2018-2022 PhotoPrism UG. All rights reserved.",
        "flags": "settings",
        "baseUri": "",
        "staticUri": "/static",
        "cssUri": "/static/build/app.81f65a5a51e0137b6cf3.css",
        "jsUri": "/static/build/app.ba67dd004f8e873b61af.js",
        "manifestUri": "/manifest.json?1673637593",
        "apiUri": "/api/v1",
        "contentUri": "/api/v1",
        "wallpaperUri": "",
        "siteUrl": "http://photoprism.host.or.ip:port/",
        "siteDomain": "photoprism.host.or.ip",
        "siteAuthor": "",
        "siteTitle": "PhotoPrism",
        "siteCaption": "",
        "siteDescription": "",
        "sitePreview": "http://photoprism.host.or.ip:port/static/img/preview.jpg",
        "legalInfo": "PhotoPrism® needs your support!",
        "legalUrl": "https://photoprism.app/membership",
        "appName": "PhotoPrism",
        "appMode": "standalone",
        "appIcon": "logo",
        "debug": false,
        "trace": false,
        "test": false,
        "demo": false,
        "sponsor": false,
        "readonly": false,
        "uploadNSFW": false,
        "public": false,
        "authMode": "password",
        "experimental": false,
        "albumCategories": null,
        "albums": [],
        "cameras": [
            {
                "ID": 5,
                "Slug": "apple-iphone-13-pro",
                "Name": "Apple iPhone 13 Pro",
                "Make": "Apple",
                "Model": "iPhone 13 Pro"
            },
            {
                "ID": 3,
                "Slug": "canon-eos-1000d",
                "Name": "Canon EOS 1000D",
                "Make": "Canon",
                "Model": "EOS 1000D"
            },
            {
                "ID": 1,
                "Slug": "zz",
                "Name": "Unknown",
                "Make": "",
                "Model": "Unknown"
            }
        ],
        "lenses": [
            {
                "ID": 4,
                "Slug": "18",
                "Name": "18",
                "Make": "",
                "Model": "18",
                "Type": ""
            },
            {
                "ID": 8,
                "Slug": "apple-iphone-13-pro-back-dual-camera-9mm-f-2-8",
                "Name": "Apple iPhone 13 Pro back dual camera 9mm f/2.8",
                "Make": "Apple",
                "Model": "iPhone 13 Pro back dual camera 9mm f/2.8",
                "Type": ""
            },
            {
                "ID": 9,
                "Slug": "apple-iphone-13-pro-back-dual-wide-camera-5-7mm-f-1-5",
                "Name": "Apple iPhone 13 Pro back dual wide camera 5.7mm f/1.5",
                "Make": "Apple",
                "Model": "iPhone 13 Pro back dual wide camera 5.7mm f/1.5",
                "Type": ""
            },
            {
                "ID": 7,
                "Slug": "apple-iphone-13-pro-back-triple-camera-5-7mm-f-1-5",
                "Name": "Apple iPhone 13 Pro back triple camera 5.7mm f/1.5",
                "Make": "Apple",
                "Model": "iPhone 13 Pro back triple camera 5.7mm f/1.5",
                "Type": ""
            },
            {
                "ID": 6,
                "Slug": "apple-iphone-13-pro-back-triple-camera-9mm-f-2-8",
                "Name": "Apple iPhone 13 Pro back triple camera 9mm f/2.8",
                "Make": "Apple",
                "Model": "iPhone 13 Pro back triple camera 9mm f/2.8",
                "Type": ""
            },
            {
                "ID": 2,
                "Slug": "ef-s18-135mm-f-3-5-5-6-is-stm",
                "Name": "EF-S18-135mm f/3.5-5.6 IS STM",
                "Make": "",
                "Model": "EF-S18-135mm f/3.5-5.6 IS STM",
                "Type": ""
            },
            {
                "ID": 3,
                "Slug": "ef-s18-55mm-f-3-5-5-6",
                "Name": "EF-S18-55mm f/3.5-5.6",
                "Make": "",
                "Model": "EF-S18-55mm f/3.5-5.6",
                "Type": ""
            },
            {
                "ID": 5,
                "Slug": "ef50mm-f-1-8-stm",
                "Name": "EF50mm f/1.8 STM",
                "Make": "",
                "Model": "EF50mm f/1.8 STM",
                "Type": ""
            },
            {
                "ID": 1,
                "Slug": "zz",
                "Name": "Unknown",
                "Make": "",
                "Model": "Unknown",
                "Type": ""
            }
        ],
        "countries": [
            {
                "ID": "zz",
                "Slug": "zz",
                "Name": "Unknown"
            }
        ],
        "people": [
            {
                "UID": "jrpkdem151t0u43v",
                "Name": "Name",
                "Keywords": [
                    "name"
                ]
            },
        ],
        "thumbs": [
            {
                "size": "fit_720",
                "use": "Mobile, TV",
                "w": 720,
                "h": 720
            },
            {
                "size": "fit_1280",
                "use": "Mobile, HD Ready TV",
                "w": 1280,
                "h": 1024
            },
            {
                "size": "fit_1920",
                "use": "Mobile, Full HD TV",
                "w": 1920,
                "h": 1200
            },
            {
                "size": "fit_2048",
                "use": "Tablets, Cinema 2K",
                "w": 2048,
                "h": 2048
            },
            {
                "size": "fit_2560",
                "use": "Quad HD, Retina Display",
                "w": 2560,
                "h": 1600
            },
            {
                "size": "fit_3840",
                "use": "Ultra HD",
                "w": 3840,
                "h": 2400
            },
            {
                "size": "fit_4096",
                "use": "Ultra HD, Retina 4K",
                "w": 4096,
                "h": 4096
            },
            {
                "size": "fit_7680",
                "use": "8K Ultra HD 2, Retina 6K",
                "w": 7680,
                "h": 4320
            }
        ],
        "mapKey": "D1K7jii3ItwO6t34RJ7S",
        "downloadToken": "blablabla1",
        "previewToken": "blablabla2",
        "disable": {
            "backups": false,
            "webdav": false,
            "settings": false,
            "places": false,
            "exiftool": false,
            "ffmpeg": false,
            "raw": false,
            "darktable": true,
            "rawtherapee": false,
            "sips": true,
            "heifconvert": true,
            "tensorflow": false,
            "faces": false,
            "classification": false
        },
        "count": {
            "all": 8013,
            "photos": 7972,
            "live": 3,
            "videos": 38,
            "cameras": 4,
            "lenses": 8,
            "countries": 2,
            "hidden": 0,
            "favorites": 0,
            "private": 0,
            "review": 8,
            "stories": 0,
            "albums": 1,
            "moments": 6,
            "months": 17,
            "folders": 38,
            "files": 8077,
            "people": 27,
            "places": 5,
            "states": 1,
            "labels": 90,
            "labelMaxPhotos": 5185
        },
        "pos": {
            "uid": "pronhbr3osl6qmrx",
            "cid": "s8:124ddb1da29",
            "utc": "2023-01-13T16:50:24Z",
            "lat": 0,
            "lng": 0
        },
        "years": [
            2023,
            2022,
            2021,
            2020,
            2019,
            2017
        ],
        "colors": [
            {
                "Example": "#AB47BC",
                "Name": "Purple",
                "Slug": "purple"
            },
            {
                "Example": "#FF00FF",
                "Name": "Magenta",
                "Slug": "magenta"
            },
            {
                "Example": "#EC407A",
                "Name": "Pink",
                "Slug": "pink"
            },
            {
                "Example": "#EF5350",
                "Name": "Red",
                "Slug": "red"
            },
            {
                "Example": "#FFA726",
                "Name": "Orange",
                "Slug": "orange"
            },
            {
                "Example": "#D4AF37",
                "Name": "Gold",
                "Slug": "gold"
            },
            {
                "Example": "#9E9E9E",
                "Name": "Grey",
                "Slug": "grey"
            },
            {
                "Example": "#212121",
                "Name": "Black",
                "Slug": "black"
            }
        ],
        "categories": [
            {
                "UID": "lrog17n2xkq0529m",
                "Slug": "animal",
                "Name": "Animal"
            },
            {
                "UID": "lrog1ct3brs6jmms",
                "Slug": "architecture",
                "Name": "Architecture"
            },
            {
                "UID": "lrog14g2esvg10tz",
                "Slug": "beach",
                "Name": "Beach"
            },
            {
                "UID": "lrog0602unq3ytzb",
                "Slug": "beverage",
                "Name": "Beverage"
            },
            {
                "UID": "lrog17n28qihjaqb",
                "Slug": "bird",
                "Name": "Bird"
            },
            {
                "UID": "lrog0af1r1qmvmi1",
                "Slug": "building",
                "Name": "Building"
            },
            {
                "UID": "lrog2vw1yia5sej5",
                "Slug": "cat",
                "Name": "Cat"
            },
            {
                "UID": "lroh83a3lvqh5q3n",
                "Slug": "church",
                "Name": "Church"
            },
            {
                "UID": "lrog0h7nznomt07u",
                "Slug": "food",
                "Name": "Food"
            },
            {
                "UID": "lrog7lo34v2jf604",
                "Slug": "historic",
                "Name": "Historic"
            },
            {
                "UID": "lrogbuxcytv0qcll",
                "Slug": "info",
                "Name": "Info"
            },
            {
                "UID": "lroghp734wnwioph",
                "Slug": "insect",
                "Name": "Insect"
            },
            {
                "UID": "lrog07g2ozkbnyqz",
                "Slug": "kitchen",
                "Name": "Kitchen"
            },
            {
                "UID": "lrokum72h0wgeg4r",
                "Slug": "monkey",
                "Name": "Monkey"
            },
            {
                "UID": "lrogaq82j23zr7q8",
                "Slug": "music",
                "Name": "Music"
            },
            {
                "UID": "lrog0n3l5vr1xp6f",
                "Slug": "nature",
                "Name": "Nature"
            },
            {
                "UID": "lrog2vw30h7cpt8a",
                "Slug": "wildlife",
                "Name": "Wildlife"
            }
        ],
        "clip": 160,
        "server": {
            "cores": 4,
            "routines": 25,
            "memory": {
                "total": 16182001664,
                "free": 451702784,
                "used": 48520192,
                "reserved": 132565024,
                "info": "Used 48 MB / Reserved 133 MB"
            }
        },
        "settings": {
            "ui": {
                "scrollbar": true,
                "zoom": false,
                "theme": "default",
                "language": "en",
                "timeZone": ""
            },
            "search": {
                "batchSize": 0
            },
            "maps": {
                "animate": 0,
                "style": ""
            },
            "features": {
                "account": true,
                "advanced": false,
                "albums": true,
                "archive": true,
                "delete": false,
                "download": true,
                "edit": true,
                "estimates": true,
                "favorites": true,
                "files": true,
                "folders": true,
                "import": true,
                "labels": true,
                "library": true,
                "logs": true,
                "moments": true,
                "people": true,
                "places": true,
                "private": true,
                "ratings": true,
                "reactions": true,
                "review": true,
                "search": true,
                "services": true,
                "settings": true,
                "share": true,
                "upload": true,
                "videos": true
            },
            "import": {
                "path": "/",
                "move": false
            },
            "index": {
                "path": "/",
                "convert": true,
                "rescan": false,
                "skipArchived": false
            },
            "stack": {
                "uuid": true,
                "meta": true,
                "name": false
            },
            "share": {
                "title": ""
            },
            "download": {
                "name": "file",
                "disabled": false,
                "originals": true,
                "mediaRaw": false,
                "mediaSidecar": false
            },
            "templates": {
                "default": "index.gohtml"
            }
        },
        "acl": {
            "albums": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "calendar": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "config": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "default": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "favorites": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "feedback": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "files": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "folders": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "labels": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "logs": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "moments": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "password": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "people": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "photos": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "places": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "services": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "settings": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "shares": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "users": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            },
            "videos": {
                "access_all": true,
                "access_library": true,
                "create": true,
                "delete": true,
                "download": true,
                "full_access": true,
                "manage": true,
                "rate": true,
                "react": true,
                "share": true,
                "subscribe": true,
                "update": true
            }
        },
        "ext": {}
    },
    "data": {
        "tokens": null,
        "shares": null
    },
    "id": "91q657799c7e713f987ef309c5073bf18a14f144687f6cd1",
    "status": "ok",
    "user": {
        "UID": "urofv1u3e7idxx09",
        "Name": "admin",
        "DisplayName": "",
        "Email": "my@email.com",
        "Role": "admin",
        "SuperAdmin": true,
        "CanLogin": true,
        "WebDAV": true,
        "CanInvite": true,
        "Details": {
            "BirthYear": 0,
            "BirthMonth": 0,
            "BirthDay": 0,
            "NameTitle": "",
            "GivenName": "",
            "MiddleName": "",
            "FamilyName": "",
            "NameSuffix": "",
            "NickName": "",
            "NameSrc": "manual",
            "Gender": "male",
            "About": "",
            "Bio": "",
            "Location": "",
            "Country": "",
            "Phone": "",
            "SiteURL": "",
            "ProfileURL": "",
            "OrgTitle": "",
            "OrgName": "",
            "OrgEmail": "",
            "OrgPhone": "",
            "OrgURL": "",
            "CreatedAt": "2023-01-13T19:20:18.249404816Z",
            "UpdatedAt": "2023-01-15T12:45:17.222709125Z"
        },
        "Settings": {
            "CreatedAt": "2023-01-13T20:36:15.820858157Z",
            "UpdatedAt": "2023-01-15T12:45:17.258641377Z"
        },
        "Thumb": "d3d9d2ec4443b78d2a66f2b34df8181136e5b8f3",
        "ThumbSrc": "manual",
        "CreatedAt": "2023-01-13T19:20:18.226026739Z",
        "UpdatedAt": "2023-01-15T12:45:17.221352044Z"
    }
}
```

### CODE REVIEW

**Comment by Vansmak** [comment]
Ty, eagerly waiting

**Comment by shamoon** [comment]
Cool, works great thanks. I was a little confused that albums contains folders too, I changed it (and tiny other thing). I suppose alternative would be to make the label "Albums + Folders" but that wouldn't really work for obvious reasons.

Thanks again

**Comment by shamoon** [comment]
(fixed linting error in main)

**Comment by Vansmak** [comment]
Thank you for this.  i run 2 instances of homepage, i updated the one in proxmox container and this widget works.  the docker via portainer stack with :latest re-pulled says Missing Widget Type: photoprism.  i would check the src dir but im not a docker expert, i just have the yaml files mounted, any help here?

**Pull request merged**
