### PR TITLE
Add gluetun widget

### PR DESCRIPTION
**Pull request by Tarow**
Added widget to support [gluetun](https://github.com/qdm12/gluetun) information:

Configuration:

```
- Gluetun:
    icon: /icons/pipe.png
    href: https://gluetun.mydomain.com
    description: VPN Client
    widget:
      type: gluetun
      url: https://gluetun.mydomain.com
```

Preview:

Gluetun_Widget

### CODE REVIEW

**Comment by shamoon** [comment]
Cheers thanks

**Comment by Tarow** [comment]
You have to specify the port of the [HTTP Control Server](https://github.com/qdm12/gluetun/wiki/HTTP-control-server-options) which is 8000 by default.

**Comment by LETRA** [comment]
> You have to specify the port of the [HTTP Control Server](https://github.com/qdm12/gluetun/wiki/HTTP-control-server-options) which is 8000 by default. And also make sure the port is mapped to the host system.

I open a question in Gluetun github page for help. Thank you https://github.com/qdm12/gluetun/discussions/1287

**Comment by astronaute-nope** [comment]
Hello, how do you make it work ? 
I cannot join it since gluetun and homepage are in another docker compose network. 
Hitting the API from my computer works though (same ip as in the service.yaml file

**Comment by LETRA** [comment]
> Hello, how do you make it work ?
> I cannot join it since gluetun and homepage are in another docker compose network.
> Hitting the API from my computer works though (same ip as in the service.yaml file

I have not succeeded. I am sorry.

**Comment by astronaute-nope** [comment]
@LETRA sorry to hear that. @Tarow any idea ? Though I guess it's more a problem of Docker Compose (networking) than of the plugin.

**Comment by astronaute-nope** [comment]
btw, the error is : 

Raw Error:
{
    "errno": -110,
    "code": "ETIMEDOUT",
    "syscall": "connect",
    "address": "1.2.3.4",
    "port": 1234
}

while it's accessible through my computer browser

**Comment by shamoon** [comment]
Please create a discussion here or discord for your separate issue rather than commenting on this PR. And yes it seems like pure networking issue with your compose setup. You may want to look at the troubleshooting guide.

**Pull request merged**
