### PR TITLE
Feature/Searchbar

### PR DESCRIPTION
**Pull request by aidenpwnz**
Searchbar for google, bing, duckduckgo and custom search providers.

Includes fixes to responsiveness and overflows for mobile.

desktop

mobile

### CODE REVIEW

**Comment by benphelps** [comment]
This is wonderful, thank you!  Would you be opposed to some CSS tweaks to bring it more inline with the rest of the design pattern?  I'll be more than happy to make the changes myself after a merge.

**Comment by aidenpwnz** [comment]
> This is wonderful, thank you!  Would you be opposed to some CSS tweaks to bring it more inline with the rest of the design pattern?  I'll be more than happy to make the changes myself after a merge.

Sure have at it! This feature definitely needs more polishing.
If you need any help let me know.

**Comment by aidenpwnz** [comment]
I think I messed up a bit the pr... Well I just added NGINX Proxy Manager service widget, shouldn't create too much trouble. Let me know if I should fix!

**Comment by benphelps** [comment]
Both parts look good, I'll pull them in and do a little cleanup tomorrow morning.  Thank you again :)

**Comment by benphelps** [comment]
@aidenpwnz Just wanted to give an update.  I've tweaked the mobile layout a bit more and pulled the styles from panels below up for the search bar.  Along with some simplification of the code.

Screenshot 2022-09-03 at 12 56 10 PM

Screenshot 2022-09-03 at 12 56 17 PM

The border radius of the inside button being ever so slightly bigger on the corners is driving me nuts but I'll leave that for another day.

**Pull request merged**
