### PR TITLE
Add flood widget

### PR DESCRIPTION
**Pull request by JigSawFr**
Add flood widget to homepage (https://github.com/jesec/flood)

image

### CODE REVIEW

**Comment by shamoon** [comment]
Question: doesnt using flood require the use of [deluge](https://gethomepage.dev/en/services/deluge/) / [qBittorrent](https://gethomepage.dev/en/services/qbittorrent/) / [rTorrent](https://gethomepage.dev/en/services/rutorrent/) / [Transmission](https://gethomepage.dev/en/services/transmission/), _every one of which we already support_? So I guess the question is why not just use those directly?

**Comment by shamoon** [comment]
Like kind seems redundant?
Screen Shot 2022-12-01 at 8 56 37 AM

Also: not working for me `error: <floodProxyHandler> HTTP 422 logging in to flood.  Data: {"message":"Validation error."}`

**Comment by JigSawFr** [comment]
> Question: doesnt using flood require the use of [deluge](https://gethomepage.dev/en/services/deluge/) / [qBittorrent](https://gethomepage.dev/en/services/qbittorrent/) / [rTorrent](https://gethomepage.dev/en/services/rutorrent/) / [Transmission](https://gethomepage.dev/en/services/transmission/), _every one of which we already support_? So I guess the question is why not just use those directly?

Not the same thing. Flood is an UI on top of qbittorent / deluge / rtorrent and Transmission.
It's not redundant as if you don't expose these torrents downloaders and only the UI, you can't use them. (like rflood hotio docker container)
Also Flood-UI is using a JSON API, same for rtorrent from jsec. So XLMRPC can't be used.
Sonarr/Radarr/Overseer also implemented communication with Flood.

**Comment by JigSawFr** [comment]
@shamoon is your test protected by an auth? or auth was disabled in Flood ?

**Comment by JigSawFr** [comment]
@shamoon if you can retry, auth is now fixed. 💯

image

**Review by shamoon — APPROVED** [review]
Fair enough, its still a little inception-y =)

And cool that fixed it

Screen Shot 2022-12-01 at 4 44 27 PM

**Comment by shamoon** [comment]
Lint errors were fixed in https://github.com/benphelps/homepage/commit/01b55a17f1aafdd8c4312dfb321b6b9caee55259

**Pull request merged**
