### PR TITLE
fix-#2056:Added null checking using lodash

### PR DESCRIPTION
**Pull request by rayansailani**
## Proposed change
Added null/undefined/empty object check using lodash library to prevent error in #2056 

Closes (#2055)

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [ ] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks but we're not going to add an entire dependency for a 1 line fix. It also wasn't added correctly to npm lock file.

Im not clear under what circumstances this situation happens, but vanilla javascript will do just fine.

Thanks anyway

**Comment by rayansailani** [comment]
Okay, can I look into fixing it with Vanilla JS ?

**Comment by shamoon** [comment]
I took care of it mate https://github.com/benphelps/homepage/commit/6483b10ebabe6803be2b8bd5fe036b7d1983614e

sorry I’m impatient

Since you’re running from source can you tell why this would even happen? I can’t reproduce it

**Comment by rayansailani** [comment]
That's great! I was looking into why this is happening at a deeper level. But I feel checking it like this would be better 
`if (!data || Object.keys(data).length === 0)` reason being `drive.available` could also throw an error at some point of time.

**Pull request closed without merging**
