### PR TITLE
Add Synology Diskstation widget & consolidate Synology proxies

### PR DESCRIPTION
**Pull request by Oupsman**
After cleanup everything, I can open again a PR for a synology diskstation widget.

### CODE REVIEW

**Comment by shamoon** [comment]
Nice thanks. 

We will still likely want to generalize the Synology proxy but will get back to you

**Comment by Oupsman** [comment]
> Nice thanks.
> 
> We will still likely want to generalize the Synology proxy but will get back to you

And I'm willing to work on that too

**Comment by JazzFisch** [comment]
@Oupsman I've consolidated the proxy logic in to a single reusable Synology proxy.  I also reduced the number of fields from 5 to 4, and changed the field names a little.  Let me know if all of this looks OK to you.  Please also test it on your local setup.

Here is what the UI looks like now:
image

**Comment by shamoon** [comment]
Awesome work @JazzFisch, makes these widgets way easier to manage

Oupsman let us know if there are any issues in testing, big thanks to you both for the collaboration! I know a lot of users are/will use these widgets

**Comment by Oupsman** [comment]
I will test it ASAP. But I've seen that you removed the total volume size, and that was an user request.

**Comment by JazzFisch** [comment]
> I will test it ASAP. But I've seen that you removed the total volume size, and that was an user request.

I went back and forth about what to put in the `Available` field.  I suppose we could do something like this:
image

**Comment by Oupsman** [comment]
Either that or 3TB / 11.5TB

That way you have both informations in the same field.

**Comment by JazzFisch** [comment]
> Either that or 3TB / 11.5TB
> 
> That way you have both informations in the same field.

As someone else commented in another thread, how often are you changing your volume size that you need to be able to see it all times?  Also, the only number that will consistently change is your available space.  Is the total volume size really that useful of a metric to have available at all times?

**Comment by Oupsman** [comment]
> 
> As someone else commented in another thread, how often are you changing your volume size that you need to be able to see it all times? Also, the only number that will consistently change is your available space. Is the total volume size really that useful of a metric to have available at all times?

I know, it was me who made this comment. I'm not sure it's an useful metric but I did not wrote this widget only for me :)

**Comment by Oupsman** [comment]
I've tested the widget, it works.

**Comment by JazzFisch** [comment]
> I've tested the widget, it works.

Which version of DSM are you running?  Also, thanks for all of the feedback.  Here's what the widget now looks like at one of its smallest sizes with wrapping.

image

How many degrees of precision do you think we need?  Right now it is set at 1, but changing that to 0 could keep the widget text from wrapping on extremely small sizes.

**Comment by divemasterjm** [comment]
> I've tested the widget, it works.

I would like to test it, can you please tell me how?
thanks

**Comment by Oupsman** [comment]
> > I've tested the widget, it works.
> 
> Which version of DSM are you running? Also, thanks for all of the feedback. Here's what the widget now looks like at one of its smallest sizes with wrapping.

Right now, only against DSM7, but I'll test it against DSM 5 very soon and against DMS6 when I recover the password of my testing VM. 

> 
> image
> 
> How many degrees of fraction precision do you think we need? Right now it is set at 1, but changing that to 0 could keep the widget text from wrapping on extremely small sizes.

I think that having a separate field for the total size is a good thing, as you can choose to not display it if you don't want it. And from my point of vue, having the percentage of free space is way more useful than the available size in bytes. If we shorten the displayed fields names, it can fit, I think.

**Comment by Oupsman** [comment]
Right now, the diskstation widget does not connect anymore to DSM 5 and 6, I'm working on it. 

Both with the same error code : 102, meaning that the API does not exist.

**Comment by Oupsman** [comment]
I think I got it : you are using a cache for datas. But if we have multiples NAS, the cache key is always the same across all widgets. As my test environnement is composed of multi NAS, the cache values are always from the DSM7 NAS.

**Comment by Oupsman** [comment]
I've corrected the code and it works : 
image

That's the homepage I'm using, yes :)

**Comment by JazzFisch** [comment]
I'm still trying to find an elegant way of keeping the `Available` field from wrapping.  Sorry for the delay on approval.  @Oupsman thanks for you testing.

**Comment by Oupsman** [comment]
> I'm still trying to find an elegant way of keeping the `Available` field from wrapping. Sorry for the delay on approval. @Oupsman thanks for you testing.

Did you saw the correction I made in your code ?

**Comment by JazzFisch** [comment]
> > I'm still trying to find an elegant way of keeping the `Available` field from wrapping. Sorry for the delay on approval. @Oupsman thanks for you testing.
> 
> Did you saw the correction I made in your code ?

I did.  Good catch on the multiple instances.

I've been able to resolve the wrapping issue.  That being said, the team is trying really hard to come up with a basic style guide and one of those pieces of guidance to use 4 fields or fewer where possible.  I know someone had asked for total volume and other metrics, but from a bear minimum, which fields do you feel are required @Oupsman?

Here's an example of 5 fields that I privately have working, but I'd prefer to get down to 4.

image

**Comment by Oupsman** [comment]
> > > I'm still trying to find an elegant way of keeping the `Available` field from wrapping. Sorry for the delay on approval. @Oupsman thanks for you testing.
> > 
> > 
> > Did you saw the correction I made in your code ?
> 
> I did. Good catch on the multiple instances.
> 
> I've been able to resolve the wrapping issue. That being said, the team is trying really hard to come up with a basic style guide and one of those pieces of guidance to use 4 fields or fewer where possible. I know someone had asked for total volume and other metrics, but from a bear minimum, which fields do you feel are required @Oupsman?
> 
> Here's an example of 5 fields that I privately have working, but I'd prefer to get down to 4.
> 
> image

As a user can select the field needed, I don't see the point ? Or is it because most users will not bother to change the default behavior of a widget ? 

If I had to get rid of a field, I'd get rid of either Available or Free and make it a custom parameter : by default, you display the Free field but a custom parameter allows you to choose between either the free size of the percent ? 

PS : I've been working on the same thing for the OPNSense widget, adding a custom parameter to either display the traffic rate or the total traffic since boot, but I'm not sure if it is a good idea.

**Comment by JazzFisch** [comment]
> As a user can select the field needed, I don't see the point ? Or is it because most users will not bother to change the default behavior of a widget ?

Yes.  Try and make functionality work for the most amount of folks out of the box.

> If I had to get rid of a field, I'd get rid of either Available or Free and make it a custom parameter : by default, you display the Free field but a custom parameter allows you to choose between either the free size of the percent ?

We don't have this feature in any of the other widgets at this time.  Something to consider, but I wonder if we're straying from the purpose of this PR.

**Comment by Oupsman** [comment]
> We don't have this feature in any of the other widgets at this time. Something to consider, but I wonder if we're straying from the purpose of this PR.

Then my opinion is we publish a widget with 4 fields, the "Available" displaying the remaining space in bytes and see if we have a feature request to display it in percentage. I'm keen to have it in percentage but if I'm the only one to want it so, I'll can leave without it : I have other ways to have the information pretty kick (a few Grafana dashboards)

**Review by JazzFisch — APPROVED** [review]

**Comment by JazzFisch** [comment]
> > We don't have this feature in any of the other widgets at this time. Something to consider, but I wonder if we're straying from the purpose of this PR.
> 
> Then my opinion is we publish a widget with 4 fields, the "Available" displaying the remaining space in bytes and see if we have a feature request to display it in percentage. I'm keen to have it in percentage but if I'm the only one to want it so, I'll can leave without it : I have other ways to have the information pretty kick (a few Grafana dashboards)

Please create a new issue to track your idea about having default visible fields with additional configurable fields as well.  That way we can discuss internally.

Thanks for all of your work and patience on this PR!

**Comment by PancakeZik** [comment]
Now that it's merged, any instructions on how to use this? Can't find it on the wiki yet.
Thank you!

**Comment by shamoon** [comment]
https://gethomepage.dev/en/services/diskstation/

**Comment by ninagrosse** [comment]
Thanks for the addition!

Reading those DSM stats needs admin privileges though, and the widget isn't compatible with 2FA. I don't want admins without 2FA on my DiskStation but I managed to get it working with a regular user.

Here is what I did:
- Added a new user named `dashboard` and gave it a password
- Put the user in the system default group
- I also disabled access to all shares and apps because I just want the user for my dashboard stats
- Save the user
- Select the user in the userlist, then select "Delegate Administration" and in the new window select the option to read system status

You now have a regular, non-admin user who can read the stats for the widget.
I hope I translated the last step right. Here's a screenshot from the German interface:
image

**Comment by avaryx** [comment]
@ninagrosse Thank you for the guidance. I am attempting to do the same, and believe I've set the user up the same way you state here. On the UI in English, I've selected:
image

My problem at this point is the fact the widget shows up, but doesn't give me any API info:
image

And the error is non-descriptive.

For this service/widget, I've defined that entry as such:
```yaml
  - Synology:
      description: NAS
      href: http://192.168.7.5:5000/
      ping: http://192.168.7.5:5000/
      icon: synology.png
      widget:
        type: diskstation
        url: http://192.168.7.5:5000
        username: homepage
        password: <removed>
```

Did you have this experience and did you find anything else to fix it?

**Comment by ninagrosse** [comment]
Okay, this is weird. When I posted my previous comment, it worked without problems. Haven't looked at my homepage since but now I get the same API Error like @avaryx

homepage log shows errors:

```
[2023-02-10T17:33:57.274Z] warn: <synologyProxyHandler> Unable to login.  Code: 402
[2023-02-10T17:33:57.274Z] warn: <synologyProxyHandler> Unable to call http://192.168.178.218:5000/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info.  code: 402, error: Authentication failed..
[2023-02-10T17:33:57.276Z] warn: <synologyProxyHandler> Unable to login.  Code: 402
[2023-02-10T17:33:57.276Z] warn: <synologyProxyHandler> Unable to call http://192.168.178.218:5000/webapi/entry.cgi?api=SYNO.Core.System.Utilization&version=1&method=get.  code: 402, error: Authentication failed..
[2023-02-10T17:33:57.279Z] warn: <synologyProxyHandler> Unable to login.  Code: 402
[2023-02-10T17:33:57.279Z] warn: <synologyProxyHandler> Unable to call http://192.168.178.218:5000/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info&type="storage".  code: 402, error: Authentication failed..
```

So does my DiskStation / DSM:
`User [dashboard] from [192.168.178.101] failed to sign in to [DSM] via [password] due to authorization failure.`

Looks like it worked at first because after I created the user, I added it to the admin group, tested the widget (worked), and only removed admin and added the delegate option later. Maybe it still worked for a while after that because of caching.

Apparently this widget - or more specifically the DSM API - needs a real admin user after all.

**Comment by MisterX2000** [comment]
I've got it working, using a normal user and delegating System monitoring.
I tried every permission and the one which was needed extra is for the Download Station Application. Now it is working without adding the user to the administrators group.
Screenshot 2023-03-12 143520
Screenshot 2023-03-12 143342
Screenshot 2023-03-12 143113

**Comment by mattconres** [comment]
Same issue I can NOT get the api user to work if it's not a part of administrators

**Comment by naziris** [comment]
Same issue:

[2023-04-08T12:57:18.543Z] warn: <synologyProxyHandler> Unable to login.  Code: 407
[2023-04-08T12:57:18.544Z] warn: <synologyProxyHandler> Unable to call https://domain:5001//webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info.  code: 407, error: Authentication failed. 2FA enabled..
[2023-04-08T12:57:18.544Z] warn: <synologyProxyHandler> Unable to login.  Code: 407
[2023-04-08T12:57:18.545Z] warn: <synologyProxyHandler> Unable to call https://domain:5001//webapi/entry.cgi?api=SYNO.Core.System.Utilization&version=1&method=get.  code: 407, error: Authentication failed. 2FA enabled..
[2023-04-08T12:57:18.551Z] warn: <synologyProxyHandler> Unable to login.  Code: 407
[2023-04-08T12:57:18.552Z] warn: <synologyProxyHandler> Unable to call https://domain:5001//webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info&type="storage".  code: 407, error: Authentication failed. 2FA enabled..

**Comment by rmohns** [comment]
Adding this for others to find in the future:
### This widget works with Synology Router Manager (SRM 1.3)

I've tested it on SRM 1.3 running on an RT2600. I have no reason to assume it won't work on other Synology router/wifi models. Below is a screenshot showing it pulling all fields successfully (if slowly):
Screenshot 2023-05-23 at 12 12 23 PM

The user must be given admin permissions 👎 boo, hiss. Create the Synology user, then edit it and set the checkbox here:
Screenshot 2023-05-23 at 12 17 52 PM

_Note:_ The widget can only show volume info for the router's boot volume, not for the SD card (if used). The SD card mounts at `/volumeUSB1/usbshare1-1`, which I suspect breaks the widget's assumptions about paths. ¯\\_(ツ)_/¯

Here is a sample from `services.yaml`:
```
    - Router:
        href: http://<address>:<port> # defaults to port 8000
        ping: http://<address>:<port>
        description: Your most fabulous Synology router
        icon: mdi-router-network
        widget:
            type: diskstation
            url: <address>:<port>
            username: docker_user_homepage # User must be given admin rights 👎
            password: <very strong password here please>
            fields: ["resources.cpu","resources.mem"]
```
For my homepage, I turned off volume (don't care) and uptime (also don't care). But they do work. Here's what the above yaml would give you:
Screenshot 2023-05-23 at 12 28 05 PM

It would be nice to be able to pull other info, but CPU & Memory are the important ones, so I'm pleased with this. Thank you to all of you who worked on creating, refining, and testing this widget!

**Pull request merged**
