### PR TITLE
Add Prowlarr widget

### PR DESCRIPTION
**Pull request by xicopitz**

### CODE REVIEW

**Comment by benphelps** [comment]
Please do not include language entries for anything other than English, and any other language natively or fluently translated.  This is to allow Weblate to make the updates on its side for the other languages, and properly mark them as needing new translations.

**Comment by xicopitz** [comment]
Roger that. Do you want me to remove them?

**Comment by benphelps** [comment]
Yes please, then I'll merge this in :)

**Comment by ShlomiPorush** [comment]
for some reason I don't know. After adding the widget of prowlarr to homepage takes a lot longer to load.

**Pull request merged**
