### PR TITLE
Add Grafana widget

### PR DESCRIPTION
**Pull request by Mbarmem**
I've added support for displaying info from Grafana
To use it:

```
type: grafana
url: http://your.grafana.ip:3000
```

Grafana

API output:

<details>
<summary>/api/alerts</summary>
<br>

```json
[
  {
    "id": 25,
    "dashboardId": 25,
    "dashboardUid": "01",
    "dashboardSlug": "server",
    "panelId": 253,
    "name": "Pi CPU Usage Alert",
    "state": "alerting",
    "newStateDate": "2022-10-09T23:18:10+03:00",
    "evalDate": "0001-01-01T00:00:00Z",
    "evalData": {
      "error": "request handler error: failed to query data"
    },
    "executionError": "request handler error: failed to query data",
    "url": "/d/01/server"
  },
  {
    "id": 26,
    "dashboardId": 25,
    "dashboardUid": "01",
    "dashboardSlug": "server",
    "panelId": 254,
    "name": "Pi Memory Usage Alert",
    "state": "alerting",
    "newStateDate": "2022-10-09T23:19:06+03:00",
    "evalDate": "0001-01-01T00:00:00Z",
    "evalData": {
      "error": "request handler error: failed to query data"
    },
    "executionError": "request handler error: failed to query data",
    "url": "/d/01/server"
  },
  {
    "id": 27,
    "dashboardId": 25,
    "dashboardUid": "01",
    "dashboardSlug": "server",
    "panelId": 233,
    "name": "Pi Temperatue Alert",
    "state": "alerting",
    "newStateDate": "2022-10-09T23:18:27+03:00",
    "evalDate": "0001-01-01T00:00:00Z",
    "evalData": {
      "error": "request handler error: failed to query data"
    },
    "executionError": "request handler error: failed to query data",
    "url": "/d/01/server"
  },
  {
    "id": 21,
    "dashboardId": 25,
    "dashboardUid": "01",
    "dashboardSlug": "server",
    "panelId": 1,
    "name": "Server CPU Usage Alert",
    "state": "ok",
    "newStateDate": "2023-02-12T04:44:02+03:00",
    "evalDate": "0001-01-01T00:00:00Z",
    "evalData": {},
    "executionError": "",
    "url": "/d/01/server"
  },
  {
    "id": 22,
    "dashboardId": 25,
    "dashboardUid": "01",
    "dashboardSlug": "server",
    "panelId": 164,
    "name": "Server Load Alert",
    "state": "ok",
    "newStateDate": "2023-02-12T04:46:09+03:00",
    "evalDate": "0001-01-01T00:00:00Z",
    "evalData": {},
    "executionError": "",
    "url": "/d/01/server"
  },
  {
    "id": 24,
    "dashboardId": 25,
    "dashboardUid": "01",
    "dashboardSlug": "server",
    "panelId": 11,
    "name": "Server Memory Alert",
    "state": "ok",
    "newStateDate": "2023-02-12T04:44:45+03:00",
    "evalDate": "0001-01-01T00:00:00Z",
    "evalData": {},
    "executionError": "",
    "url": "/d/01/server"
  },
  {
    "id": 23,
    "dashboardId": 25,
    "dashboardUid": "01",
    "dashboardSlug": "server",
    "panelId": 232,
    "name": "Server Temperature Alert",
    "state": "ok",
    "newStateDate": "2023-02-06T05:10:04+03:00",
    "evalDate": "0001-01-01T00:00:00Z",
    "evalData": {},
    "executionError": "",
    "url": "/d/01/server"
  }
]
```
</details>

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks. I cleaned up the code and also you weren't using the labels correctly (also fixed that for fileflows).

In general this seems OK but for a service that churns through hoards of data just showing the alerts felt a little sparse. I added the stats endpoint with # dashboards and data sources, there's other info in there. Let me know your thoughts.

Screenshot 2023-02-13 at 8 53 43 PM

Also btw this widget hasn't been requested by anyone and we're trying to target 'higher value' ones (though not explicitly a rule yet). Feel free to find other widget FR with 'up-votes'

**Comment by Mbarmem** [comment]
I skipped the stats endpoint after wasting countless as I couldn't figure out the authentication part (yup, newbie here XD).

I'll have a look at other FR too.

**Comment by shamoon** [comment]
Yes you need to include the username / pw to the widget, it works fine that way. I'll include that in to the docs 👍

**Comment by shamoon** [comment]
I'll have to re-create this PR, your last merge created an issue in the git history, no worries

**Pull request closed without merging**
