### PR TITLE
Add Nextcloud widget

### PR DESCRIPTION
**Pull request by Mbarmem**
I've added support for displaying info from Nextcloud #257 
To use it:

```
- Nextcloud:
    icon: nextcloud.png
    href: https://your.nextcloud.fqdn
    description: Online Collaboration Platform
    widget:
      type: nextcloud
      url: https://your.nextcloud.fqdn
      fields: ["cpuload", "memoryusage", "freespace","activeusers", "shares"] //optional
      username: your.user.name
      password: your.password.or.app.password
```

image

API output:

<details>
<summary>ocs/v2.php/apps/serverinfo/api/v1/info?format=json</summary>
<br>

```json
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
      "nextcloud": {
        "system": {
          "version": "25.0.1.1",
          "theme": "",
          "enable_avatars": "yes",
          "enable_previews": "yes",
          "memcache.local": "\\OC\\Memcache\\APCu",
          "memcache.distributed": "\\OC\\Memcache\\Redis",
          "filelocking.enabled": "yes",
          "memcache.locking": "\\OC\\Memcache\\Redis",
          "debug": "no",
          "freespace": 26138219937792,
          "cpuload": [
            0.6513671875,
            1.16259765625,
            0.890625
          ],
          "mem_total": 65862656,
          "mem_free": 53291008,
          "swap_total": 997376,
          "swap_free": 928768,
          "apps": {
            "num_installed": 51,
            "num_updates_available": 0,
            "app_updates": []
          }
        },
        "storage": {
          "num_users": 1,
          "num_files": 46805,
          "num_storages": 12,
          "num_storages_local": 1,
          "num_storages_home": 1,
          "num_storages_other": 10
        },
        "shares": {
          "num_shares": 0,
          "num_shares_user": 0,
          "num_shares_groups": 0,
          "num_shares_link": 0,
          "num_shares_mail": 0,
          "num_shares_room": 0,
          "num_shares_link_no_password": 0,
          "num_fed_shares_sent": 0,
          "num_fed_shares_received": 0
        }
      },
      "server": {
        "webserver": "nginx/1.20.2",
        "php": {
          "version": "8.0.25",
          "memory_limit": 536870912,
          "max_execution_time": 3600,
          "upload_max_filesize": 1073741824,
          "opcache": {
            "opcache_enabled": true,
            "cache_full": false,
            "restart_pending": false,
            "restart_in_progress": false,
            "memory_usage": {
              "used_memory": 49998616,
              "free_memory": 84195944,
              "wasted_memory": 23168,
              "current_wasted_percentage": 0.017261505126953125
            },
            "interned_strings_usage": {
              "buffer_size": 12582448,
              "used_memory": 5168288,
              "free_memory": 7414160,
              "number_of_strings": 83143
            },
            "opcache_statistics": {
              "num_cached_scripts": 2156,
              "num_cached_keys": 4120,
              "max_cached_keys": 16229,
              "hits": 470160,
              "start_time": 1676455795,
              "last_restart_time": 0,
              "oom_restarts": 0,
              "hash_restarts": 0,
              "manual_restarts": 0,
              "misses": 2172,
              "blacklist_misses": 0,
              "blacklist_miss_ratio": 0,
              "opcache_hit_rate": 99.54015395950306
            },
            "jit": {
              "enabled": false,
              "on": false,
              "kind": 5,
              "opt_level": 4,
              "opt_flags": 6,
              "buffer_size": 0,
              "buffer_free": 0
            }
          },
          "apcu": {
            "cache": {
              "num_slots": 4099,
              "ttl": 0,
              "num_hits": 35015,
              "num_misses": 1772,
              "num_inserts": 1788,
              "num_entries": 182,
              "expunges": 0,
              "start_time": 1676455795,
              "mem_size": 133168,
              "memory_type": "mmap"
            },
            "sma": {
              "num_seg": 1,
              "seg_size": 33554312,
              "avail_mem": 33381296
            }
          },
          "extensions": [
            "Core",
            "phpdbg_webhelper",
            "date",
            "libxml",
            "pcre",
            "zlib",
            "filter",
            "hash",
            "json",
            "readline",
            "Reflection",
            "SPL",
            "session",
            "cgi-fcgi",
            "bcmath",
            "bz2",
            "ctype",
            "curl",
            "dom",
            "fileinfo",
            "ftp",
            "gd",
            "gmp",
            "iconv",
            "standard",
            "intl",
            "ldap",
            "mbstring",
            "openssl",
            "pcntl",
            "PDO",
            "pgsql",
            "posix",
            "imap",
            "SimpleXML",
            "sodium",
            "sqlite3",
            "xml",
            "xmlwriter",
            "zip",
            "exif",
            "mysqlnd",
            "pdo_pgsql",
            "pdo_sqlite",
            "Phar",
            "xmlreader",
            "pdo_mysql",
            "apcu",
            "igbinary",
            "redis",
            "memcached",
            "imagick",
            "mcrypt",
            "smbclient",
            "libsmbclient",
            "Zend OPcache"
          ]
        },
        "database": {
          "type": "mysql",
          "version": "10.6.12",
          "size": "89325568"
        }
      },
      "activeUsers": {
        "last5minutes": 1,
        "last1hour": 1,
        "last24hours": 1
      }
    }
  }
}
```
</details>

### CODE REVIEW

**Comment by shamoon** [comment]
Cool thanks. We’re going to limit the number of blocks to 4, so we’ll have to choose one to lop off :)

**Comment by Mbarmem** [comment]
We can remove the shares.

**Comment by shamoon** [comment]
Awesome, works great thanks. I removed the last block.

**Comment by amitjethani** [comment]
Feature request: It would be great if all of the fields were supported, but only up to 4 were shown. That way, a user can customize their dashboard further. As an example, a user may want to see `shares` but skip the `freespace`. If a user specifies more than 4, just show the first 4.

**Pull request merged**
