### PR TITLE
Fix: Show container status if health is an empty string

### PR DESCRIPTION
**Pull request by eanmclaughlin**
If data.health is an empty string, ?? will accept it and not use the right side value; instead, we should use || which treats empty string as false and returns the right side value. This will show "RUNNING" in the status box if health is "".

### CODE REVIEW

**Comment by eanmclaughlin** [comment]
Exemplary screenshot:

image

**Comment by shamoon** [comment]
In what situation is health ""?

**Comment by shamoon** [comment]
Sorry misread this! =)

**Comment by shamoon** [comment]
Thanks

**Pull request merged**
