### PR TITLE
Feature: mealie widget

### PR DESCRIPTION
**Pull request by joncrangle**
## Proposed change

Adds a widget for [Mealie](https://mealie.io/) self-hosted recipe management app.
Mealie widget

Mealie has a [well-documented API](https://nightly.mealie.io/api/redoc/) that exposes two endpoints that can be queried for statistics. I chose to query the group `Get Statistics` API that returns:
```json
{
  "totalRecipes": 0,
  "totalUsers": 0,
  "totalCategories": 0,
  "totalTags": 0,
  "totalTools": 0
}
```
 I omitted `totalTools` to keep with the Homepage standard of limiting widgets to four fields. The group `Get Statistics` API can be queried with a user-generated long-lived API token.

The other option would be to query the admin `Get Admin Statistics` that returns:
```json
{
  "totalRecipes": 0,
  "totalUsers": 0,
  "totalGroups": 0,
  "uncategorizedRecipes": 0,
  "untaggedRecipes": 0
}
```
This API can be queried by providing the admin username and password.

I felt that most users would prefer seeing categories and tags vs total groups and uncategorized or untagged recipes. I found that I needed to provide a url to the mealie-frontend (default port 9925) rather than the backend API.

```yaml
#services.yaml
- Mealie:
        href: http://mealie-frontend.host.or.ip:9925
        icon: mealie.png
        description: Recipes
        widget:
            type: mealie
            url: http://mealie-frontend.host.or.ip:9925
            key: apikey
```

Closes # https://github.com/benphelps/homepage/discussions/1790

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/142
- [x] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Nice, clean work thanks! 👍

**Comment by crispybegs** [comment]
is this live? i tried 

```
 - Mealie:
        icon: mealie.png
        href: http://192.168.1.49:9925
        widget:
          type: mealie
          url: http://192.168.1.49:9925
          key: [redacted]
```

but get 

Screenshot 2023-08-20 at 21 16 16

**Comment by shamoon** [comment]
No, its not

**Comment by deweycd** [comment]
Which version of Mealie is this for? I have tried v0.5.6 from https://hub.docker.com/r/hkotel/mealie with no success.

**Pull request merged**
