### PR TITLE
Minecraft server status widget

### LINKED ISSUE #1042: [Feature Request] Minecraft server status
### Description

This would be a widget that sends a request to the following URL:

https://mcapi.us/server/status?ip={IP_ADDRESS}&port={PORT}. 

This returns a json indicating if the sever is online, how many players are online and what the IP/name of the server is.

This would be similar to the smart app on the fenrus dashboard, I have a link to their code below:
https://github.com/revenz/Fenrus/tree/master/apps/Smart/Minecraft

### Other

I got quite a bit of a busy upcoming weeks, but if I find the time I could do it.

### PR DESCRIPTION
**Pull request by Sairenity**
## Proposed change

Adds a minecraft server status widget
image

Closes #1042 

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/45
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by Sairenity** [comment]
This is the first time I'm contributing to an OSS project, so if you have any feedback at all, please let me know :)

**Comment by shamoon** [comment]
Thanks for the PR, welcome to FOSS :)

So just to clarify this widget hits a third-party service which is what actually pings the server? Is there a reason you’re not bypassing that and hitting the server directly? And did you check the TOS of that service to see if this would be ok?

**Comment by Sairenity** [comment]
Hi shamoon, thanks for the warm welcome :)

> So just to clarify this widget hits a third-party service which is what actually pings the server? Is there a reason you’re not bypassing that and hitting the server directly?

Yep, exactly. The reason I'm not hitting the server directly is because minecraft itself sadly doesn't provide a REST api to query server status information. [The protocol minecraft uses](https://wiki.vg/Query) is a bit more... involved, and if I don't absolutely have to re-implement it, I'd rather use a proxy to get the infos 😅 

> And did you check the TOS of that service to see if this would be ok?

The service I used doesn't have an explicit TOS, and even after some digging, the only thing I'm able to find which implicitly grants permission is the [API Docs](https://api.mcsrvstat.us/)

If you don't feel comfortable with this service, which I would totally understand, I could go hunt for another with more acceptable explicit TOS?

Kind regards, 
Sairenity

**Comment by Sairenity** [comment]
of course, I could also pull in something like [minecraft-ping-js](https://www.npmjs.com/package/minecraft-ping-js), and write a proxy in src/utils/proxy/handlers... both would work for me.

**Comment by shamoon** [comment]
Ok thanks. As long as they don’t explicitly say this isn’t allowed it should be ok. The custom proxy thing can get messy. it’s probably worth noting in the docs how this works and your widget.js can probably just hard-code the URL part no? Or is the software that runs that service available to self-host (in which case the main url could be different I suppose)

Thanks so much, we’ll take a look at the actual code soon.

**Comment by Sairenity** [comment]
> Ok thanks. As long as they don’t explicitly say this isn’t allowed it should be ok. 

great to hear :)

> The custom proxy thing can get messy.

I cobbled together a proxy that actually works... I'm now quite tempted to just use this instead. [Here's the gist to the minecraft proxy handler](https://gist.github.com/Sairenity/0c69dd0ab76a1ac52bcaf90e4f7270d8)

> your widget.js can probably just hard-code the URL part no? Or is the software that runs that service available to self-host (in which case the main url could be different I suppose)

yeah, that's fair criticism. I left the URL configurable, just in case somebody wanted to build a compatible drop-in replacement.

**Review by shamoon — CHANGES_REQUESTED** [review]
Hey, we talked about this and even though we usually like to avoid custom proxies we agreed the version where uses can connect to their own servers without relying on this third party service would be preferable. Let us know if you need help working this out, shouldn't be too bad.

Thanks for your contribution

**Comment by shamoon** [comment]
Nice thanks! Is this ready to test?

**Comment by Sairenity** [comment]
heya, yep this is now ready from my side. mind taking a look?

**Comment by Sairenity** [comment]
fwiw, here's a sample `services.yaml` to quickly check if everything is behaving well.

```yaml
- Minecraft Servers:
    - Hypixel:
        description: mc.hypixel.net
        icon: https://api.mcsrvstat.us/icon/mc.hypixel.net
        widget:
          type: minecraft
          domain: mc.hypixel.net
    - Inexistant:
        description: some inexistant server
        icon: https://api.mcsrvstat.us/icon/does.not.exist
        widget:
          type: minecraft
          domain: does.not.exist
```

**Comment by shamoon** [comment]
Cool, is this also compatible with something like https://github.com/itzg/docker-minecraft-server that a user would use for self-hosted?

**Comment by Sairenity** [comment]
> Cool, is this also compatible with something like https://github.com/itzg/docker-minecraft-server that a user would use for self-hosted?

Yep, it totally should be! I've verified it's working for a locally-hosted server by plugging in the IP directly.
I'll test the docker scenario a bit later, because this is also interesting for the documentation. Being able to directly reference the docker container like such would be quite neat:

```yaml
- Minecraft Servers:
    - Local Docker Minecraft Server:
        widget:
          type: minecraft
          domain: docker-container-name-here
```

**Comment by shamoon** [comment]
Awesome, this works great with your examples and self-hosted. The thing you mentioned above about referencing containers should already work, thats a docker thing

Self-hosted:
Screenshot 2023-02-28 at 8 50 02 AM

Others:
Screenshot 2023-02-28 at 8 35 43 AM
Screenshot 2023-02-28 at 8 35 47 AM

See my changes, obviously one thing is I moved the proxy since it won't be used by other widgets. I also changed the URL stuff to use the `url` key which is standard here. Your examples above will need to have: `url: http://mc.hypixel.net` as a result, but for self-hosted it'd be `url: http://localhost:25565` or similar.

Please let me know any thoughts, feel free to tweak more of course. Docs will need to be updated per all this.

**Comment by shamoon** [comment]
> _technically,_ what we're using to try connect to a minecraft server isn't an URL, since we're not using http or https, but that's just me splitting hairs 🤓

Hmm, I was going to go and look if it does use http or not, wasn’t sure. Yea, I agree it bugs me too :) if it’s not technically correct but wondering if that outweighs the benefit of using the `url` key that is otherwise pretty standard

**Comment by 21st-centuryman** [comment]
@Sairenity Just wanna say great job on this. Welcome to FOSS.

**Comment by shamoon** [comment]
Lets go with `url: udp://mc.hypixel.net` =)

**Comment by Sairenity** [comment]
> Lets go with `url: udp://mc.hypixel.net` =)
that's a great suggestion!

Thank you for all the help, also with the docs.

**Comment by mgrimace** [comment]
The minecraft ping / proxy handler used here seems to reference service port 25565, which appears to work for java edition, but does not work (at least for me) for a self-hosted bedrock server (e.g., xbox compatible) which instead uses port 19132 as the default port. For example, I use 
udp://[serverIP]:19132 but it results in: 

Screenshot 2023-06-19 at 8 47 04 PM

Despite the server being online/connectable on PC/xbox, etc.
Any idea on the widget side to add bedrock compatibility?

**Comment by shamoon** [comment]
There’s an open FR for that https://github.com/benphelps/homepage/discussions/1179

**Comment by Sairenity** [comment]
I considered bedrock out-of-scope initially.

I could take a look how easy it's API is to integrate 👍

**Comment by SX86** [comment]
Any progress on getting it compatible with Bedrock?
I thought I was going crazy until I saw that last comment from Jun 20 :)

**Comment by shamoon** [comment]
https://github.com/gethomepage/homepage/discussions/1179#discussioncomment-6647755

**Pull request merged**
