### PR TITLE
Basic support for Docker Swarm services

### PR DESCRIPTION
**Pull request by kolessios**
This PR adds basic support for obtaining the status and statistics of services deployed in Docker Swarm partially solving #348 

I have chosen to use almost the same method used to obtain this data for containers:

- Still using the `container` config parameter in `services.yaml`
- The new code is used as failover, i.e. if the container does not exist, it tries to find it as a Swarm service. At first glance I have not detected a considerable delay using this method, in any case maybe in the future it would be better to use a different config parameter to go directly to the new code.
- I have modified the code structure a little by choosing to enclose positive results in conditions leaving `error: "not found"` at the end.

---

It is possible to test the new code by creating the following files in the project directory:

`docker-compose.yml`
```yml
version: "3.8"

volumes:
  speedtest_data:

services:
  # Homepage
  homepage:
    image: homepage:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"

  # Speedtest Tracker
  speedtest:
    image: henrywhitaker3/speedtest-tracker:latest
    restart: unless-stopped
    volumes:
      - speedtest_data:/config
    environment:
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
```

`data/docker.yaml`
```yml
---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Docker-Integration

# my-docker:
#   host: 127.0.0.1
#   port: 2375

my-docker:
  socket: /var/run/docker.sock
```

`data/services.yaml`
```yml
---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- My First Group:
    - Speedtest Tracker Service:
        server: my-docker
        container: homepage_speedtest
```

And then executing:

```sh
# Build Dockerfile and save the image locally
# Swarm mode does not allow the use of build: in docker-compose.yml
docker build --pull --rm -f Dockerfile -t homepage:latest .

# In case of not being in Swarm mode
docker swarm init

# Deploy on Swarm mode
docker stack deploy homepage -c docker-compose.yml
```

### CODE REVIEW

**Comment by JazzFisch** [comment]
Thank you for submitting your PR.  Can you please add optional `swarm` boolean field support in `docker.yaml` so you aren't required to go through the fallback logic each time.

**Comment by benphelps** [comment]
> Thank you for submitting your PR. Can you please add optional `swarm` boolean field support in `docker.yaml` so you aren't required to go through the fallback logic each time.

I agree with this solution, it's clean and will keep the load homepage generates as small as possible.

**Review by shamoon — CHANGES_REQUESTED** [review]
See https://github.com/benphelps/homepage/pull/449#issuecomment-1299190842

**Comment by shamoon** [comment]
Closed in favor of #660

**Pull request closed without merging**
