### PR TITLE
Added custom API widget

### PR DESCRIPTION
**Pull request by denispapec**
## Proposed change

This adds support for custom self-hosted API and third party API.
Detailed usage can be found in docs: https://github.com/benphelps/homepage-docs/pull/147

For the simplicity of testing, examples use public API that is not interesting for homepage usage :sweat_smile: 
image

<details>
<summary>Public API example 1</summary>

```yaml
        widget:
          type: custom
          url: https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current_weather=true&hourly=temperature_2m,relativehumidity_2m,windspeed_10m
          refreshInterval: 60000
          mappings:
            - field:
                hourly:
                  time: 108
              label: Hour
            - field:
                hourly:
                  temperature_2m: 108
              format: number
              label: Temperature
            - field:
                hourly:
                  relativehumidity_2m: 108
              label: Humidity
              format: percent
```
</details>

<details>
<summary>Public API example 2</summary>

```yaml
        widget:
          type: custom
          url: https://rickandmortyapi.com/api/character/1
          mappings:
            - field: name
              label: Name
            - field: status
              label: Status
            - field:
                origin: name
              label: Origin
            - field:
                location: name
              label: Location
```
</details>

<details>
<summary>Public API example 3</summary>

```yaml
        widget:
          type: custom
          url: https://pokeapi.co/api/v2/pokemon/ditto
          refreshInterval: 5000
          mappings:
            - field: name
              label: Name
            - field:
                moves:
                  0:
                    move: name
              label: Main move
```
</details>

Closes https://github.com/benphelps/homepage/discussions/1219

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/147
- [x] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Cool idea. A little nervous about the "support" requests 😅 but this is clever, I think people will dig it. I can take a look soon

**Comment by shamoon** [comment]
Two small things in the meantime:
- i think we should rename this to something like "custom json" or "custom api"? Thinking we want to leave room for other widgets of the custom ilk
- we need to enforce a minimum refresh, other places use 1500 (resources use 1000 but 1500 more consistent with service widgets)

**Comment by shamoon** [comment]
Nice mate. I did go ahead and rename it, just to preserve the namespace. And I saw you already had the refresh minimum.

Thanks, I think people will dig this.

**Comment by janek202** [comment]
Thank you for this widget, it works great with Supermicro's Redfish for IPMI.


Is there a way to use this widget with an API key?
I tried integrating it with Syncthing REST API (https://docs.syncthing.net/dev/rest) using 'key: API_KEY', and 'password: API_KEY', but it doesn't seem to be working for me.

**Pull request merged**
