### PR TITLE
Add Channels DVR Server widget

### PR DESCRIPTION
**Pull request by maddox**
## Proposed change

This adds a new service widget for [Channels DVR Server](https://getchannels.com/dvr-server/) that powers [Channels](https://getchannels.com)

Docs pull: https://github.com/benphelps/homepage-docs/pull/79

https://github.com/benphelps/homepage/discussions/1385

## Screenshot

image

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thank you for the PR but we only accept new service widgets that have been requested & voted for by the community, please see https://gethomepage.dev/en/more/development/

Please feel free to re-submit at a later time.

**Comment by AnUnknownGenome** [comment]
I would like to see this widget included.

**Comment by shamoon** [comment]
You and Jmcguire525 really on the same page today! ;-b

Anyway, it's cool, we can re-open. As the ones who field all the issues etc we have to be cognizant of the maintenance side of things...

Since this app doesn't seem like something we can easily spin up please at least include some example(s) of API output we can test with.

**Comment by ehosch** [comment]
Is it possible to get this widget to work when the dvr is remote/behind a proxy.  I am running homepage on an external server so that I can quickly see if my home network is online.  @maddox Can you add an authorization code field or something to get it to work that way?

**Pull request merged**
