### PR TITLE
Glances Charts Widget

### PR DESCRIPTION
**Pull request by benphelps**
## Proposed change

This introduces a new widget type that displays information from glances hosts,

It looks like this:
Screenshot 2023-08-01 at 3 57 41 AM

And is configured like this (in `services.yaml`):
```yaml
- Graphs:
    - CPU Usage:
        widget:
          type: glances
          url: http://192.168.0.201:61208
          metric: cpu
    - Network Usage:
        widget:
          type: glances
          url: http://192.168.0.201:61208
          metric: network:enp0s25
    - CPU Temp:
        widget:
          type: glances
          url: http://192.168.0.201:61208
          metric: sensor:Package id 0
    - Disk I/O:
        widget:
          type: glances
          url: http://192.168.0.201:61208
          metric: disk:sdb
```

## Type of change

New service widget.

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/131
- [x] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by benphelps** [comment]
This still needs some cleanup, but I wanted to get it pushed out so others can try to break it.

**Comment by shamoon** [comment]
Awesome mate. I look forward to kicking the tires (will find some time soon)

**Comment by benphelps** [comment]
Here's the latest UI, for each of the metric types.

Screenshot_2023-08-01_at_4 43 52_PM

**Comment by shamoon** [comment]
This is sick and very satisfying to use, I think people are gonna love it. I had no issues getting it setup and havent had any unexpected issues so far or been able to break it.

The only thing I've thought so far is if you put in an incorrect metric e.g. `sensor:xyz` you get a nextjs error as opposed to something a little more graceful, but that seems really minor.

Bravo, mate

Screenshot 2023-08-01 at 2 23 03 PM

**Review by shamoon — APPROVED** [review]

**Comment by itzTheMeow** [comment]
is there a possibility for a disk usage widget like this? maybe list disks inside the widget. i dont see anything in the documentation for disk space usage

**Comment by shamoon** [comment]
If you'd like a new feature, please open a feature request, adding comments on closed PRs won't be very visible for the community anyway.

**Pull request merged**
