### PR TITLE
Add Synology DiskStation widget

### LINKED ISSUE #523: [Feature Request] Synology Download Station widget
### Description

Is there any chance to get widget similar to one for qbittorrent but for Synology Download Station?

### Other

_No response_

### PR DESCRIPTION
**Pull request by JazzFisch**
closes #523

### CODE REVIEW

**Comment by shamoon** [comment]
Nice. I presume I can’t test this without their hardware?

**Comment by c4rver** [comment]
It doesn't work for me with API version 2, I changed it to version 3 in line 8 from proxy.js and it worked (sorry I don't know how to use git yet)

`const authApi = "{url}/webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account={username}&passwd={password}&session=DownloadStation&format=cookie"`

**Comment by JazzFisch** [comment]
> It doesn't work for me with API version 2, I changed it to version 3 in line 8 from proxy.js and it worked (sorry I don't know how to use git yet)
> 
> `const authApi = "{url}/webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account={username}&passwd={password}&session=DownloadStation&format=cookie"`

Which version of DSM are you using?

**Comment by Magelo** [comment]
It doesn't work for  me either. I'm using Homepage docker container, and I don't know if I can modify something in a docker to test @c4rver solution.

I'm on DSM 7.1.1-42962 Update 2

**Comment by c4rver** [comment]
> Which version of DSM are you using?

Hi, I'm using DSM 7.1.1-42962 Update 1

**Comment by retmas-gh** [comment]
This should be renamed to "Synology Download Station widget" as it, per source, takes data only from this app, not the whole system (DiskStation) with which I would expect to get data about things like CPU, RAM, whole unit network interfaces stats not only this one app etc.
https://www.synology.com/pl-pl/dsm/packages/DownloadStation

**Comment by danielwerner86** [comment]
I agree with the above poster. While I appreciate the work so far, I hope there will be a widget with the general Synology stats too. :)

**Comment by IIIdefconIII** [comment]
anyone have an example to use this without 2fa?

**Comment by IIIdefconIII** [comment]
@c4rver does the diskstation widget still works for you?

**Comment by c4rver** [comment]
Yes, I'm using the disk station widget and works fine

**Comment by IIIdefconIII** [comment]
@c4rver canyou tell me how you got the volume status my diskatation widget gives me a whole other outpout:

```
   - Synology DSM:
        description: Network Attached Storage (:5001)
        ping: https://10.3.1.5:5001
        icon: synology-dsm.png
        href: https://10.3.1.5:5001
        widget:
            type: diskstation
            url: https://10.3.1.5:5001
            username: username
            password: password
```
image

**Comment by c4rver** [comment]
I used this:

{{syno_baseurl}}/webapi/entry.cgi?api=SYNO.FileStation.List&version=2&method=list_share&additional=%5B%22volume_status%22%2C%22owner%2Ctime%22%5D

And it retruns all mount point folders, included the volume status:
`"volume_status": {
                        "freespace": 108075147264,
                        "readonly": false,
                        "totalspace": 979635990528
                    }`

**Comment by IIIdefconIII** [comment]
> I used this:
> 
> {{syno_baseurl}}/webapi/entry.cgi?api=SYNO.FileStation.List&version=2&method=list_share&additional=%5B%22volume_status%22%2C%22owner%2Ctime%22%5D
> 
> And it retruns all mount point folders, included the volume status:
> `"volume_status": {
>                         "freespace": 108075147264,
>                         "readonly": false,
>                         "totalspace": 979635990528
>                     }`

Whre can i adjust that don't know where to be honest

**Comment by c4rver** [comment]
> just in the services.yaml like this? i think i dont understand correctly
> 
> ```
>    - Synology TEST:
>         description: Network Attached Storage (:5001)
>         ping: https://10.3.1.5:5001
>         icon: synology-dsm.png
>         href: https://10.3.1.5:5001
>         widget:
>             type: diskstation
>             url: https://10.3.1.5:5001//webapi/entry.cgi?api=SYNO.FileStation.List&version=2&method=list_share&additional=%5B%22volume_status%22%2C%22owner%2Ctime%22%5D
> ```

No, in the code.

**Comment by IIIdefconIII** [comment]
> 

no idea where and how to do that

**Comment by c4rver** [comment]
I did it before they publish the diskstation widget, i'm reviewing the widget in code and maybe some other data can be added.

You should ask to @shamoon

**Comment by shamoon** [comment]
Instead of resurrecting the comments on a merged PR I would suggest starting a discussion or asking in chat if you have a specific question like this.

I'm not sure what you're asking though, you can't "adjust" the code of this project unless you are running from source.

**Comment by junyuyuan** [comment]
[2023-06-15T11:58:07.519Z] warn: <synologyProxyHandler> Unable to call http://192.168.110.155:5000/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info&type="storage".  code: 400, error: Authentication failed..
[2023-06-15T11:58:07.547Z] warn: <synologyProxyHandler> Unable to login.  Code: 400
[2023-06-15T11:58:07.547Z] warn: <synologyProxyHandler> Unable to call http://192.168.110.155:5000/webapi/entry.cgi?api=SYNO.Core.System&version=3&method=info.  code: 400, error: Authentication failed..
[2023-06-15T11:58:07.595Z] warn: <synologyProxyHandler> Unable to login.  Code: 400



        icon: synology-dsm.png
        widget:
          type: diskstation
          url: http://192.168.110.155:5000
          username: username
          password: {{HOMEPAGE_VAR_PASSWORD}}

**Pull request merged**
