### PR TITLE
Add OpenDTU Widget

### PR DESCRIPTION
**Pull request by LucaDev**
## Proposed change

Adds an OpenDTU Widget (as discussed in https://github.com/benphelps/homepage/discussions/2055)
image

Closes https://github.com/benphelps/homepage/discussions/2055

## Type of change

- [X] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [X] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/160
- [X] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [X] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks. 

Since openDTU doesnt seem like a trivial thing to setup and test, if you could supply sample data that would be great thanks.

**Comment by LucaDev** [comment]
Sure! 
As I'm not producing any energy right now, the current output is zero. The livedata endpoint is returning the following json object for my current installation with two inverters (700W + 800W):
```json
{"inverters":[{"serial":"114190548558","name":"Carport 800W","order":0,"data_age":8023,"poll_enabled":true,"reachable":false,"producing":false,"limit_relative":100,"limit_absolute":800,"AC":{"0":{"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":227.1000061,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"Power DC":{"v":0.600000024,"u":"W","d":1},"YieldDay":{"v":2396,"u":"Wh","d":0},"YieldTotal":{"v":26.84399986,"u":"kWh","d":3},"Frequency":{"v":49.97000122,"u":"Hz","d":2},"PowerFactor":{"v":0,"u":"","d":3},"ReactivePower":{"v":0,"u":"var","d":1},"Efficiency":{"v":0,"u":"%","d":3}}},"DC":{"0":{"name":{"u":""},"Power":{"v":0.300000012,"u":"W","d":1},"Voltage":{"v":18.29999924,"u":"V","d":1},"Current":{"v":0.02,"u":"A","d":2},"YieldDay":{"v":1182,"u":"Wh","d":0},"YieldTotal":{"v":13.18599987,"u":"kWh","d":3},"Irradiation":{"v":0.073170729,"u":"%","d":3,"max":410}},"1":{"name":{"u":""},"Power":{"v":0.300000012,"u":"W","d":1},"Voltage":{"v":18.29999924,"u":"V","d":1},"Current":{"v":0.02,"u":"A","d":2},"YieldDay":{"v":1214,"u":"Wh","d":0},"YieldTotal":{"v":13.65799999,"u":"kWh","d":3},"Irradiation":{"v":0.073170729,"u":"%","d":3,"max":410}}},"INV":{"0":{"Temperature":{"v":29,"u":"°C","d":1}}},"events":1},{"serial":"114182936304","name":"Carport 700W","order":0,"data_age":7793,"poll_enabled":true,"reachable":false,"producing":false,"limit_relative":100,"limit_absolute":700,"AC":{"0":{"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":228.3999939,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"Power DC":{"v":1.299999952,"u":"W","d":1},"YieldDay":{"v":2673,"u":"Wh","d":0},"YieldTotal":{"v":610.7410278,"u":"kWh","d":3},"Frequency":{"v":49.97999954,"u":"Hz","d":2},"PowerFactor":{"v":0,"u":"","d":3},"ReactivePower":{"v":0,"u":"var","d":1},"Efficiency":{"v":0,"u":"%","d":3}}},"DC":{"0":{"name":{"u":""},"Power":{"v":0.600000024,"u":"W","d":1},"Voltage":{"v":21.29999924,"u":"V","d":1},"Current":{"v":0.029999999,"u":"A","d":2},"YieldDay":{"v":1333,"u":"Wh","d":0},"YieldTotal":{"v":305.8640137,"u":"kWh","d":3},"Irradiation":{"v":0.142857149,"u":"%","d":3,"max":420}},"1":{"name":{"u":""},"Power":{"v":0.699999988,"u":"W","d":1},"Voltage":{"v":21.29999924,"u":"V","d":1},"Current":{"v":0.039999999,"u":"A","d":2},"YieldDay":{"v":1340,"u":"Wh","d":0},"YieldTotal":{"v":304.8770142,"u":"kWh","d":3},"Irradiation":{"v":0.166666657,"u":"%","d":3,"max":420}}},"INV":{"0":{"Temperature":{"v":34.20000076,"u":"°C","d":1}}},"events":1}],"total":{"Power":{"v":0,"u":"W","d":1},"YieldDay":{"v":5069,"u":"Wh","d":0},"YieldTotal":{"v":637.585022,"u":"kWh","d":3}},"hints":{"time_sync":false,"radio_problem":false,"default_password":false}}
```

**Review by shamoon — APPROVED** [review]
No judgements on the power generation, just need to test, works great =)

One small thing is to remove the de translation file changes (which I did), all translations should flow through weblate

Thanks again

Screenshot 2023-09-26 at 12 59 40 PM

**Comment by LucaDev** [comment]
Whoops. Didn't know that. Thanks for merging!
Maybe we should add that information to the guidelines.

**Pull request merged**
