### PR TITLE
Add Health checks widget

### PR DESCRIPTION
**Pull request by rommelkott**
## Proposed change

First time open source contributor.

I implemented a widget for [healthchecks.io](https://healthchecks.io/). It shows the current status of a project. (online, offline, etc)

This closes https://github.com/benphelps/homepage/issues/965

image
image
image

### Widget configuration
    widget:
        type: healthchecks
        key: <YOUR_API_KEY>
        uuid: <YOUR_CHECK_UUID>

Let me know if you need any changes done. 👍

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/39
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
Thanks, and welcome to open source :)

This does need to be changed to use our Block format, have a look at some other widgets to see. Perhaps a block for up / down and one for the last ping. This would also allow you to simplify the widget to get rid of or at least pare down the relative date stuff

**Comment by rommelkott** [comment]
Thank you for your feedback! 

I have changed the widget to use the block component. However, I am unsure of how to improve the relative date function as you suggested. Instead, I have simplified the function to only display the date instead of relative time. This also had the added benefit of decluttering the common.json file.

If you have any further ideas or vision for the widget, please let me know, and I will make the necessary changes. 😄

**Comment by shamoon** [comment]
Cheers, works great overall. Made some minor code changes and I did change the date to use month number to be even shorter, minor stuff.

**Review by shamoon — APPROVED** [review]

**Comment by rommelkott** [comment]
Thanks again! I'll review the changes and see what I can learn from it. 😄

**Comment by jeanpaulrh** [comment]
Hi, would it be possible to make the widget work even with a selfhosted healthchecks? I think it onlyh require the ability to specify the server url

**Comment by rommelkott** [comment]
> Hi, would it be possible to make the widget work even with a selfhosted healthchecks? I think it onlyh require the ability to specify the server url

Sure, I can make the change.

**Comment by mendoncart** [comment]
Awesome addition!
Is it possible to show more than one healthcheck, or show how many are offline and how many are online?

**Comment by Churator** [comment]
> Awesome addition! Is it possible to show more than one healthcheck, or show how many are offline and how many are online?

+1 from me.

**Pull request merged**
