### PR TITLE
Feature: UrBackup Widget

### PR DESCRIPTION
**Pull request by sdonchez**
## Proposed change
[UrBackup](https://www.urbackup.org/) is a centralized backup solution that supports making file and image backups of computers within a local network or over the internet. It exposes an API that already has a [nodeJS wrapper](https://github.com/bartmichu/node-urbackup-server-api).

image

I've authored [urbackup-plugin](https://github.com/sdonchez/homepage/tree/urbackup-widget), which implements a widget for reporting summary backup health data and backup disk usage. I've also provided an [update to the docs](https://github.com/sdonchez/homepage-docs/tree/urbackup-widget) to document this new widget.

image

I believe I've met all of the linting and code style guidelines, but I'm far from a Next.JS expert, so I'm open to feedback and corrections.

Thanks!

Closes #1733

## Type of change

- [X] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [X] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: [Docs PR 130](https://github.com/benphelps/homepage-docs/pull/130)
- [X] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines). See #1733 for confirmation of 5 upvotes
- [X] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
This is a bit of a complex widget, requires a new dependency and its own proxy but I appreciate all of that might not be easily circumvented, the api wrapper itself seems complex.

Why not just check if the `totalUsed` is supplied instead of a separate option for `diskUsage`?

Also, since this seems non-trivial to setup for testing can you provide an example of the API output?

5 votes in 5 hours is quite fast.

**Comment by sdonchez** [comment]
I agree about the complexity - I started out trying to avoid the dependency, but I ended up more or less implementing its core functionality all over again (except with doubtless more bugs), so I decided to include it instead. 

As far as API output, does a screenshot of browser developer tools work?

RE: total used, it's making a separate API call to get that info, so I wanted to give users the ability to opt out of it if they don't care about that information. 

RE: upvotes - I agree, I was surprised. Full disclosure, one of them may have been a slightly coerced friend, but he's actually thinking about using it, not just padding the metrics.

**Comment by shamoon** [comment]
> I agree about the complexity - I started out trying to avoid the dependency, but I ended up more or less implementing its core functionality all over again (except with doubtless more bugs), so I decided to include it instead. 

Yea I was looking at the login logic in the wrapper and it's got all kinds of error handling etc that seems annoying (and un-wise) to re-implement here, so I agree.

> As far as API output, does a screenshot of browser developer tools work?

I suppose, but copy & pasting the actual text is easier... I need to test out the widget so I need sample(s) of the API output.

> RE: total used, it's making a separate API call to get that info, so I wanted to give users the ability to opt out of it if they don't care about that information. 

Yea that's a good move I'm just saying use the presence of that field in the `fields` array instead of a separate top-level Boolean to do it. Make sense?

**Comment by sdonchez** [comment]
> > RE: total used, it's making a separate API call to get that info, so I wanted to give users the ability to opt out of it if they don't care about that information.
> 
> Yea that's a good move I'm just saying use the presence of that field in the `fields` array instead of a separate top-level Boolean to do it. Make sense?

I think I missed something fundamental here - I've somehow been using homepage for a year without realizing that the "fields" param exists for service widgets. I've added logic in my latest commit to account for that, and updated the docs correspondingly

 >> As far as API output, does a screenshot of browser developer tools work?
 >
 > I suppose, but copy & pasting the actual text is easier... I need to test out the widget so I need sample(s) of the API output.

Probably should have clarified, but I'm assuming you want data from the actual response the urbackup server's api returns, not some other layer in this chain of calls. If I'm wrong, please let me know.

Example response for the getStatus operation:
```
{
    "admin": true,
    "allow_add_client": true,
    "allow_extra_clients": true,
    "allow_modify_clients": true,
    "client_downloads": [
        {
            "id": 6,
            "name": "Hostname"
        },
        {
            "id": 5,
            "name": "Hostname2"
        },
    ],
    "curr_version_num": 2005003100,
    "curr_version_str": "2.5.31",
    "extra_clients": [
        {
            "hostname": "192.168.178.58",
            "id": "1",
            "online": false
        },
        {
            "hostname": "192.168.178.45",
            "id": "2",
            "online": false
        }
    ],
    "has_status_check": true,
    "no_file_backups": false,
    "no_images": false,
    "remove_client": true,
    "server_identity": "bf6eI7IylpEfnHwtCNMj",
    "server_pubkey": "bf6eI7IylpEfnHwtCNMj#fingerprint=61:64:73:66:61:64:73:66:6B:6A:6C:6B:68:6A:6B:68:61:66:64:73:6B:6C:3B:6A:61:64:73:66:6B:6C:3B:6A",
    "status": [
        {
            "client_version_string": "2.5.24",
            "delete_pending": "",
            "file_ok": false,
            "groupname": "",
            "id": 6,
            "image_ok": true,
            "ip": "-",
            "last_filebackup_issues": 0,
            "lastbackup": 1690333437,
            "lastbackup_image": 1690364734,
            "lastseen": 1690334114,
            "name": "Hostname",
            "online": false,
            "os_simple": "windows",
            "os_version_string": "Microsoft Windows 10 Education  (build 19045), 64-bit",
            "processes": [],
            "status": 0,
            "uid": "tHY43po34ThE4f8G"
        },
        {
            "client_version_string": "2.5.24",
            "delete_pending": "",
            "file_ok": true,
            "groupname": "",
            "id": 5,
            "image_ok": true,
            "ip": "192.168.239.156",
            "last_filebackup_issues": 0,
            "lastbackup": 1690416492,
            "lastbackup_image": 1690267688,
            "lastseen": 1690665103,
            "name": "Hostname2",
            "online": true,
            "os_simple": "windows",
            "os_version_string": "Microsoft Windows 10 Education  (build 19045), 64-bit",
            "processes": [],
            "status": 0,
            "uid": "aGF54T6h6rt12DTrF"
        },
    ]
}
```

Example response for the getUsage operation:
```
{
    "reset_statistics": "true",
    "usage": [
        {
            "files": 3.40392e+11,
            "images": 4.00641e+11,
            "name": "Hostname",
            "used": 7.41033e+11
        },
        {
            "files": 1.97397e+11,
            "images": 1.75363e+11,
            "name": "Hostname2",
            "used": 3.7276e+11
        },
    ]
}
```
Full disclosure, identifying information is spoofed here, but values are representative (and not being used anyway)

**Comment by shamoon** [comment]
Thanks, I'll test soon.

You don't need to explicitly check for all fields, homepage actually handles that (default being show all), just the total used one to functionally make it "opt-in"

Lmk if that makes sense, I can show you what I mean of course

**Comment by shamoon** [comment]
I took the liberty. Besides some small syntax stuff, I dont see a reason to create named functions that get used only once. Similarly stats-helper is only used by this widget so might as well contain the functions in there, which is what other widgets do.

Let me know if you have any concerns. Widget works great, thanks.

Screenshot 2023-07-29 at 9 59 37 PM
Screenshot 2023-07-29 at 9 59 51 PM

**Review by shamoon — APPROVED** [review]

**Comment by sdonchez** [comment]
Appreciate all your help with this. Changes make sense to me!

**Comment by shamoon** [comment]
Awesome.

FYI, something about the pnpm lock file was wrong, which makes sense since it looked like dozens of dependencies were updated when it should only be a few for this. I reverted that and re-did it

**Comment by Nonoss117** [comment]
Great job,

it seems "maxDays" parameter not working properly, or I didn't understand.
For 2 clients, the last backup was 2 days ago.
see my post here:
https://github.com/benphelps/homepage/discussions/1733#discussioncomment-6587845

**Pull request merged**
