### PR TITLE
solving docker multiple names

### PR DESCRIPTION
**Pull request by CiyLei**
Bug fix: Correct handling of docker multiple names

### CODE REVIEW

**Comment by shamoon** [comment]
what is the situation youre solving here?

**Comment by CiyLei** [comment]
I have a container with multiple names
image

before,The first name contains /,I don't know how to fill in the **container** of **server.yaml**
image

after,I can fill out postgres
image

**Comment by shamoon** [comment]
Yea, I guess with all that information why not just use `/joplin-server/pg`?

Anyway, this change seems fine thanks

**Comment by CiyLei** [comment]
Because `/api/docker/status/joplin-server/pg/server` will not be parsed correctly

**Comment by shamoon** [comment]
Ah, the slash in the name, anyway thanks

**Pull request merged**
