### PR TITLE
Fix: ping unit display for speedtest widget

### PR DESCRIPTION
**Pull request by juanmanuelbc**
## Proposed change

IMO, "unit indicator" must be displayed in a separate mode from its "number" (maybe I'm very fussy)...

Before: imatge

After: imatge

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
I think its ok as-is

**Comment by juanmanuelbc** [comment]
Let me insist on this change, @shamoon...

Anywhere I look in the project `unitDisplay: "narrow"` is not the standard (and I've reviewed the whole project)...

Some examples:

imatge

imatge

Even there are some initial screenshots that shows the standard I'm talking about (https://github.com/benphelps/homepage/blob/main/images/1.png):

imatge

Sorry for being so annoying, but I love this project and I want it to be as perfect as it can be, lol...

**Comment by juanmanuelbc** [comment]
Allow me to insist, again, about this change, @shamoon...

Some screenshots, just to see that it is (everywhere) and it has to be the standard:
imatge
imatge
imatge

So, please, consider this change again... :pray:

Thanks in advance!!!

**Comment by shamoon** [comment]
You deleted the branch so I made the changes directly in `main`. I think we can be done with this yes?

**Comment by juanmanuelbc** [comment]
> You deleted the branch so I made the changes directly in `main`. I think we can be done with this yes?

Yes, for sure!!! If you want me to make a new branch and a new PR, just tell me...

Thank you!!!

**Pull request closed without merging**
