### PR TITLE
Add Kopia widget

### PR DESCRIPTION
**Pull request by Mbarmem**
I've added support for displaying info from Kopia 
To use it:

```
- Kopia:
    icon: kopia.png
    href: https://your.kopia.ip:51515
    description: Backup Management
    widget:
      type: kopia
      url: https://your.kopia.ip:51515
      username: your.user.name
      password: your.password
```

image

API output:

<details>
<summary>api/v1/sources</summary>
<br>

```json
{
  "localUsername": "root",
  "localHost": "root",
  "multiUser": true,
  "sources": [
    {
      "source": {
        "host": "root",
        "userName": "root",
        "path": "/appdata"
      },
      "status": "IDLE",
      "schedule": {
        "timeOfDay": [
          {
            "hour": 1,
            "min": 0
          }
        ]
      },
      "lastSnapshot": {
        "id": "9cc8d00xxxxxxxx",
        "source": {
          "host": "root",
          "userName": "root",
          "path": "/appdata"
        },
        "description": "",
        "startTime": "2023-02-16T22:00:00.002254055Z",
        "endTime": "2023-02-16T22:01:49.578911321Z",
        "stats": {
          "totalSize": 67401456438,
          "excludedTotalSize": 118160,
          "fileCount": 30917,
          "cachedFiles": 139311,
          "nonCachedFiles": 30917,
          "dirCount": 43807,
          "excludedFileCount": 18,
          "excludedDirCount": 50,
          "ignoredErrorCount": 0,
          "errorCount": 0
        },
        "rootEntry": {
          "name": "root",
          "type": "d",
          "mode": "0755",
          "mtime": "2023-02-16T17:15:50.137623024Z",
          "uid": 1000,
          "gid": 1000,
          "obj": "ke5ca30b44f2b0ae3948c0273bada5a15",
          "summ": {
            "size": 67401456438,
            "files": 170228,
            "symlinks": 0,
            "dirs": 43807,
            "maxTime": "2023-02-16T22:01:00.5275526Z",
            "numFailed": 0
          }
        }
      },
      "nextSnapshotTime": "2023-02-18T01:00:00+03:00"
    }
  ]
}
```
</details>

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks. Again, no requests for this one.

would it be more helpful to have something like “next run: in 3 days” or “last run” or something like that instead of some of the other blocks? I don’t use kopia but eg thinking if I was I would perhaps want to know that it ran recently and / or will again soon.

I think there are some other code style things but will test out later

**Comment by Mbarmem** [comment]
How about this?

image

**Comment by shamoon** [comment]
Yea, like that. I was kind of imagining the 'last run' would also be some kind of date / time. The issue with relative times is they can get kinda long but in general I was thinking how to keep them short, "1h ago", "1d ago". Only issue is it also depends how often people have these running. What do you think? Again I don't actually use Kopia so would be worth looking at how it works

**Comment by Mbarmem** [comment]
Since this is a backup software, knowing the status of the last run makes more sense than time. If the backup failed, I can log in and check why, whereas run date and time gives no information whether the backup was successful or not.

**Comment by shamoon** [comment]
Yes that’s true, I was thinking it would mean last _successful_ run but not sure exactly how kopia works (or its API). If that is possible it would be valuable imho eg “uh oh I haven’t had a successful backup for 5 days? let me look what’s wrong”.

Not that I feel super strongly just trying to maximize usefulness, esp since there are no other opinions on what data to show

**Comment by Mbarmem** [comment]
There is no direct way to display the date & time for last successful run. It can be done indirectly though.

Here are the api outputs:
 
<details>
<summary>api/v1/sources</summary>
<br>

```json
{
  "localUsername": "root",
  "localHost": "root",
  "multiUser": true,
  "sources": [
    {
      "source": {
        "host": "root",
        "userName": "root",
        "path": "/appdata"
      },
      "status": "IDLE",
      "schedule": {
        "timeOfDay": [
          {
            "hour": 1,
            "min": 0
          }
        ]
      },
      "lastSnapshot": {
        "id": "9cc8d00xxxxxxxx",
        "source": {
          "host": "root",
          "userName": "root",
          "path": "/appdata"
        },
        "description": "",
        "startTime": "2023-02-16T22:00:00.002254055Z",
        "endTime": "2023-02-16T22:01:49.578911321Z",
        "stats": {
          "totalSize": 67401456438,
          "excludedTotalSize": 118160,
          "fileCount": 30917,
          "cachedFiles": 139311,
          "nonCachedFiles": 30917,
          "dirCount": 43807,
          "excludedFileCount": 18,
          "excludedDirCount": 50,
          "ignoredErrorCount": 0,
          "errorCount": 0
        },
        "rootEntry": {
          "name": "root",
          "type": "d",
          "mode": "0755",
          "mtime": "2023-02-16T17:15:50.137623024Z",
          "uid": 1000,
          "gid": 1000,
          "obj": "ke5ca30b44f2b0ae3948c0273bada5a15",
          "summ": {
            "size": 67401456438,
            "files": 170228,
            "symlinks": 0,
            "dirs": 43807,
            "maxTime": "2023-02-16T22:01:00.5275526Z",
            "numFailed": 0
          }
        }
      },
      "nextSnapshotTime": "2023-02-18T01:00:00+03:00"
    }
  ]
}
```
</details>

<details>
<summary>api/v1/tasks</summary>
<br>

```json
{
  "tasks": [
    {
      "id": "43",
      "startTime": "2023-02-18T03:21:05.523954173+03:00",
      "endTime": "2023-02-18T03:21:05.527732501+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "42",
      "startTime": "2023-02-18T02:21:05.51679899+03:00",
      "endTime": "2023-02-18T02:21:05.527985784+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "41",
      "startTime": "2023-02-18T01:21:05.500838768+03:00",
      "endTime": "2023-02-18T01:21:10.321691053+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "40",
      "startTime": "2023-02-18T01:00:00.000700788+03:00",
      "endTime": "2023-02-18T01:02:07.849433977+03:00",
      "kind": "Snapshot",
      "description": "root@xxserver:/xx at 2023-02-18T01:00:00+03:00",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": {
        "Cached Bytes": {
          "value": 50511027281,
          "units": "bytes",
          "level": ""
        },
        "Cached Files": {
          "value": 136359,
          "level": ""
        },
        "Errors": {
          "value": 0,
          "level": "error"
        },
        "Excluded Directories": {
          "value": 22,
          "level": ""
        },
        "Excluded Files": {
          "value": 9,
          "level": ""
        },
        "Hashed Bytes": {
          "value": 17841574814,
          "units": "bytes",
          "level": ""
        },
        "Hashed Files": {
          "value": 51787,
          "level": ""
        },
        "Processed Bytes": {
          "value": 68352602095,
          "units": "bytes",
          "level": ""
        },
        "Processed Files": {
          "value": 188146,
          "level": ""
        },
        "Uploaded Bytes": {
          "value": 8995824895,
          "units": "bytes",
          "level": ""
        }
      }
    },
    {
      "id": "3f",
      "startTime": "2023-02-18T00:21:05.615488671+03:00",
      "endTime": "2023-02-18T00:21:05.619036372+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "3e",
      "startTime": "2023-02-17T23:21:05.612680707+03:00",
      "endTime": "2023-02-17T23:21:05.616155794+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "3d",
      "startTime": "2023-02-17T22:21:05.610842934+03:00",
      "endTime": "2023-02-17T22:21:05.614717698+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "3c",
      "startTime": "2023-02-17T21:21:05.607314094+03:00",
      "endTime": "2023-02-17T21:21:05.610777577+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "3b",
      "startTime": "2023-02-17T20:21:05.604454672+03:00",
      "endTime": "2023-02-17T20:21:05.607827331+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "3a",
      "startTime": "2023-02-17T19:21:05.599504713+03:00",
      "endTime": "2023-02-17T19:21:05.603192887+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "39",
      "startTime": "2023-02-17T18:21:05.595197664+03:00",
      "endTime": "2023-02-17T18:21:05.598662878+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "38",
      "startTime": "2023-02-17T17:21:05.592462429+03:00",
      "endTime": "2023-02-17T17:21:05.596610093+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "37",
      "startTime": "2023-02-17T16:21:05.590471462+03:00",
      "endTime": "2023-02-17T16:21:05.593929526+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "36",
      "startTime": "2023-02-17T15:21:05.587490216+03:00",
      "endTime": "2023-02-17T15:21:05.591039847+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "35",
      "startTime": "2023-02-17T14:21:05.582360026+03:00",
      "endTime": "2023-02-17T14:21:05.58625556+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "34",
      "startTime": "2023-02-17T13:21:05.579498796+03:00",
      "endTime": "2023-02-17T13:21:05.584499915+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "33",
      "startTime": "2023-02-17T12:21:05.577203525+03:00",
      "endTime": "2023-02-17T12:21:05.581080856+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "32",
      "startTime": "2023-02-17T11:21:05.573159931+03:00",
      "endTime": "2023-02-17T11:21:05.577354694+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "31",
      "startTime": "2023-02-17T10:21:05.56839427+03:00",
      "endTime": "2023-02-17T10:21:05.57228434+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "30",
      "startTime": "2023-02-17T09:21:05.563212595+03:00",
      "endTime": "2023-02-17T09:21:05.567185923+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "2f",
      "startTime": "2023-02-17T08:21:05.560451802+03:00",
      "endTime": "2023-02-17T08:21:05.564225474+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "2e",
      "startTime": "2023-02-17T07:21:05.557481798+03:00",
      "endTime": "2023-02-17T07:21:05.561517959+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "2d",
      "startTime": "2023-02-17T06:21:05.555051117+03:00",
      "endTime": "2023-02-17T06:21:05.558351098+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "2c",
      "startTime": "2023-02-17T05:21:05.553318068+03:00",
      "endTime": "2023-02-17T05:21:05.556919566+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "2b",
      "startTime": "2023-02-17T04:21:05.550144127+03:00",
      "endTime": "2023-02-17T04:21:05.556093695+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "2a",
      "startTime": "2023-02-17T03:21:05.547478151+03:00",
      "endTime": "2023-02-17T03:21:05.552416104+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "29",
      "startTime": "2023-02-17T02:21:05.544837522+03:00",
      "endTime": "2023-02-17T02:21:05.55082456+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "28",
      "startTime": "2023-02-17T01:21:05.497914811+03:00",
      "endTime": "2023-02-17T01:21:10.964734987+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "27",
      "startTime": "2023-02-17T01:00:00.001013096+03:00",
      "endTime": "2023-02-17T01:01:49.696567147+03:00",
      "kind": "Snapshot",
      "description": "root@xxserver:/xx at 2023-02-17T01:00:00+03:00",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": {
        "Cached Bytes": {
          "value": 51089687171,
          "units": "bytes",
          "level": ""
        },
        "Cached Files": {
          "value": 139311,
          "level": ""
        },
        "Errors": {
          "value": 0,
          "level": "error"
        },
        "Excluded Directories": {
          "value": 22,
          "level": ""
        },
        "Excluded Files": {
          "value": 9,
          "level": ""
        },
        "Hashed Bytes": {
          "value": 16311769291,
          "units": "bytes",
          "level": ""
        },
        "Hashed Files": {
          "value": 30918,
          "level": ""
        },
        "Processed Bytes": {
          "value": 67401456462,
          "units": "bytes",
          "level": ""
        },
        "Processed Files": {
          "value": 170229,
          "level": ""
        },
        "Uploaded Bytes": {
          "value": 8527862036,
          "units": "bytes",
          "level": ""
        }
      }
    },
    {
      "id": "26",
      "startTime": "2023-02-17T00:21:05.578754238+03:00",
      "endTime": "2023-02-17T00:21:05.582822193+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "25",
      "startTime": "2023-02-16T23:21:05.576394392+03:00",
      "endTime": "2023-02-16T23:21:05.580240111+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "24",
      "startTime": "2023-02-16T22:21:05.572668541+03:00",
      "endTime": "2023-02-16T22:21:05.576412818+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "23",
      "startTime": "2023-02-16T21:21:05.570730043+03:00",
      "endTime": "2023-02-16T21:21:05.574478928+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "22",
      "startTime": "2023-02-16T20:21:05.566394139+03:00",
      "endTime": "2023-02-16T20:21:05.570247926+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "21",
      "startTime": "2023-02-16T19:21:05.561495214+03:00",
      "endTime": "2023-02-16T19:21:05.56542784+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "20",
      "startTime": "2023-02-16T18:21:05.556992046+03:00",
      "endTime": "2023-02-16T18:21:05.560460267+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "1f",
      "startTime": "2023-02-16T17:21:05.552616621+03:00",
      "endTime": "2023-02-16T17:21:05.55601389+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "1e",
      "startTime": "2023-02-16T16:21:05.550009634+03:00",
      "endTime": "2023-02-16T16:21:05.554137148+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "1d",
      "startTime": "2023-02-16T15:21:05.547441635+03:00",
      "endTime": "2023-02-16T15:21:05.551809752+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "1c",
      "startTime": "2023-02-16T14:21:05.54301943+03:00",
      "endTime": "2023-02-16T14:21:05.546999017+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "1b",
      "startTime": "2023-02-16T13:21:05.54069672+03:00",
      "endTime": "2023-02-16T13:21:05.544555263+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "1a",
      "startTime": "2023-02-16T12:21:05.537750568+03:00",
      "endTime": "2023-02-16T12:21:05.541643608+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "19",
      "startTime": "2023-02-16T11:21:05.535198372+03:00",
      "endTime": "2023-02-16T11:21:05.539059989+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "18",
      "startTime": "2023-02-16T10:21:05.530301465+03:00",
      "endTime": "2023-02-16T10:21:05.534358081+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "17",
      "startTime": "2023-02-16T09:21:05.528470517+03:00",
      "endTime": "2023-02-16T09:21:05.532508578+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "16",
      "startTime": "2023-02-16T08:21:05.525898045+03:00",
      "endTime": "2023-02-16T08:21:05.52980385+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "15",
      "startTime": "2023-02-16T07:21:05.523512666+03:00",
      "endTime": "2023-02-16T07:21:05.527667445+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "14",
      "startTime": "2023-02-16T06:21:05.518949435+03:00",
      "endTime": "2023-02-16T06:21:05.522816835+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "13",
      "startTime": "2023-02-16T05:21:05.513596726+03:00",
      "endTime": "2023-02-16T05:21:05.517507015+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    },
    {
      "id": "12",
      "startTime": "2023-02-16T04:21:05.508769893+03:00",
      "endTime": "2023-02-16T04:21:05.51686818+03:00",
      "kind": "Maintenance",
      "description": "Periodic maintenance",
      "status": "SUCCESS",
      "progressInfo": "",
      "counters": null
    }
  ]
}
```
</details>

**Comment by shamoon** [comment]
Let me know your thoughts on this, **not saying we have to go this route**. If errors = 0 we assume last run was success and show the relative date, if not show failed. Gets back down to 1 API call.

Screenshot 2023-02-17 at 11 46 59 PM

**Comment by Mbarmem** [comment]
> One thing I notices is that the status always shows "Idle", even if it is currently running.

Works fine on my end.

image

**Pull request merged**
