### PR TITLE
Add evcc widget

### PR DESCRIPTION
**Pull request by emre-54**
## Add evcc as widget to homepage dashbaord

it would be nice to have evcc widgets on homepage dashboards.

I currently have the following data points connected. See photo
The data points are currently translated into German and English.

pnpm lint didn´t find errors 

grafik

## API Output:
```
{
    "result": {
        "auth": {
            "vehicles": {}
        },
        "battery": [
            {
                "power": 436,
                "soc": 99,
                "capacity": 0
            }
        ],
        "batteryCapacity": 0,
        "batteryConfigured": true,
        "batteryPower": 436,
        "batterySoc": 99,
        "bufferSoc": 90,
        "bufferStartSoc": 0,
        "currency": "EUR",
        "greenShare": 0.9938583534167768,
        "gridConfigured": true,
        "gridEnergy": 835980,
        "gridPower": 79,
        "homePower": 3324.9998931884766,
        "loadpoints": [
            {
                "chargeCurrent": 14,
                "chargeCurrents": [
                    13.652999877929688,
                    13.951000213623047,
                    13.664999961853027
                ],
                "chargeDuration": 1030000000000,
                "chargePower": 9538.000106811523,
                "chargeRemainingDuration": 28735000000000,
                "chargeRemainingEnergy": 71111.11111111111,
                "chargeTotalImport": 319.26810194444477,
                "chargedEnergy": 0,
                "chargerFeatureIntegratedDevice": false,
                "chargerIcon": null,
                "charging": true,
                "connected": true,
                "connectedDuration": 0,
                "enabled": true,
                "guardAction": "inactive",
                "guardRemaining": 0,
                "maxCurrent": 16,
                "minCurrent": 6,
                "minSoc": 0,
                "mode": "pv",
                "phaseAction": "inactive",
                "phaseRemaining": 0,
                "phasesActive": 3,
                "phasesConfigured": 0,
                "phasesEnabled": 3,
                "planActive": false,
                "pvAction": "inactive",
                "pvRemaining": 0,
                "sessionCo2PerKWh": null,
                "sessionEnergy": 0,
                "sessionPrice": null,
                "sessionPricePerKWh": null,
                "sessionSolarPercentage": 0,
                "targetEnergy": 0,
                "targetSoc": 100,
                "targetTime": "0001-01-01T00:00:00Z",
                "title": "<<REMOVED>>",
                "vehicleCapacity": 64,
                "vehicleDetectionActive": false,
                "vehicleFeatureOffline": true,
                "vehicleIcon": "car",
                "vehicleIdentity": "<<REMOVED>>",
                "vehiclePresent": true,
                "vehicleRange": 0,
                "vehicleSoc": 0,
                "vehicleTargetSoc": 0,
                "vehicleTitle": "<<REMOVED>>"
            }
        ],
        "prioritySoc": 70,
        "pv": [
            {
                "power": 12348
            }
        ],
        "pvConfigured": true,
        "pvPower": 12348,
        "residualPower": 0,
        "savingsAmount": 47.02184948080182,
        "savingsEffectivePrice": 0.09080639056751952,
        "savingsGridCharged": 13.304078611064616,
        "savingsSelfConsumptionCharged": 218.9099137839934,
        "savingsSelfConsumptionPercent": 94.27076789221606,
        "savingsSince": "2023-04-17T19:39:09+02:00",
        "savingsTotalCharged": 232.21399239505803,
        "siteTitle": "<<REMOVED>>",
        "smartCostAvailable": false,
        "smartCostLimit": 0,
        "smartCostUnit": "EUR",
        "sponsor": "<<REMOVED>>",
        "sponsorTokenExpires": 0,
        "tariffEffectivePrice": 0.07981922568607636,
        "tariffFeedIn": 0.0785,
        "tariffGrid": 0.2933,
        "vehicles": [
            "<<REMOVED>>"
        ],
        "version": "0.117.3"
    }
}
```
## Docs:
https://github.com/benphelps/homepage-docs/pull/99
Closes #1458

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
Thanks for the PR.

A few things:
- please submit a docs PR as noted
- please provide sample API output as I think this requires some kind of hardware etc for testing
- Widgets cannot have more than 4 blocks so you'll have to remove one
- please don't make any changes to translation files other than the English one

**Comment by emre-54** [comment]
fulfilled all reqs now

**Comment by emre-54** [comment]
no its watt per hour so Wh

**Comment by shamoon** [comment]
Awesome thanks. Works great, you'll see my changes besides adding the units are super minor things regarding code style etc.

**Review by shamoon — APPROVED** [review]

**Pull request merged**
