### PR TITLE
New ping-indicator styles

### PR DESCRIPTION
**Pull request by LucaDev**
## Proposed change

Adds ping indicator styles "dot" and "basic":
Bildschirmfoto 2023-09-27 um 13 33 13
image

Closes: https://github.com/benphelps/homepage/discussions/1289

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [ ] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [X] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by LucaDev** [comment]
I'd love to hear some feedback before finalizing and documenting this

**Comment by sonarun** [comment]
Thank you so much for working on this! 

Personally, I like having the option for dots as an indicator vs the ping times. However; I feel that the dots could be resized or larger for glancability.

I have created a mockup of my proposal. Basically, by making the text of the dot "text-[12px]" and overriding the parent style with "background-color: transparent;"  What do you think?

Screenshot 2023-09-27 at 19 00 00 GMT+2

**Comment by benphelps** [comment]
This looks good to me, I also like the style for dots that @sonarun has proposed.

**Review by benphelps — APPROVED** [review]
Everything looks fine to me.

**Comment by LucaDev** [comment]
> Thank you so much for working on this!
> 
> Personally, I like having the option for dots as an indicator vs the ping times. However; I feel that the dots could be resized or larger for glancability.
> 
> I have created a mockup of my proposal. Basically, by making the text of the dot "text-[12px]" and overriding the parent style with "background-color: transparent;" What do you think?
> 
> Screenshot 2023-09-27 at 19 00 00 GMT+2

I do think your approach is quite a bit prettier but the conditional styling adds more complexity to the code as it is right now. I'll probably refactor the whole class later this day to better fit in the conditional styling.

**Comment by LucaDev** [comment]
I might have to add the dot style indicator option to docker and kubernetes services as well to make your dashboard look consistent 🤔

**Comment by benphelps** [comment]
> I might have to add the dot style indicator option to docker and kubernetes services as well to make your dashboard look consistent 🤔

That would be a sweet addition to go along with this, I know quite a few people want the old style dots back.

Also, I'm having second thoughts about using the literal dot character here, I feel a div with the `rounded-full` and `bg` classed and a explicit size would work better.

**Comment by LucaDev** [comment]
You might be right. I'll have a look at it.
My first draft of the dots as @sonarun proposed them:
image

**Comment by Nonoss117** [comment]
Same for me, I like the style for dots that @sonarun has proposed.

**Comment by LucaDev** [comment]
@benphelps while alowing for more control, I kinda like the design and simplicity of the current approach. What do you think @sonarun?

**Comment by LucaDev** [comment]
I think we should try to generalize the service components (ping, kubernetes-status, status, etc.) to remove all the very similar HTML code. What do you think @benphelps?
See: 
image

**Comment by sonarun** [comment]
> @benphelps while alowing for more control, I kinda like the design and simplicity of the current approach. What do you think @sonarun?

All of this looks great to me! Thank you for doing all of this work! I Think that a lot of people will really appreciate the change.

**Comment by LucaDev** [comment]
I'd suggest the following plan:

1. I'll rename the pingStyle property to statusStyle 
2. This PR will get merged for now
3. In a later PR we'll gerneralize all service types as I suggested in my previous commment implementing the statusStyle for all types

What do you think?

**Comment by benphelps** [comment]
> I'd suggest the following plan:
> 
>     1. I'll rename the pingStyle property to statusStyle
> 
>     2. This PR will get merged for now
> 
>     3. In a later PR we'll gerneralize all service types as I suggested in my previous commment implementing the statusStyle for all types
> 
> 
> What do you think?

I think that works well, we want to get this one out for a release anyways.

> I'd suggest the following plan:
> 
>     1. I'll rename the pingStyle property to statusStyle
> 
>     2. This PR will get merged for now
> 
>     3. In a later PR we'll gerneralize all service types as I suggested in my previous commment implementing the statusStyle for all types
> 
> 
> What do you think?

Sounds good to me, and we can get this in the next release.

**Comment by VlaK0r** [comment]
Nothing has changed
image

**Comment by rkison** [comment]
I really like the way the dots look

SCR-20230929-pegj

**Pull request merged**
