### PR TITLE
Feature: UniFi Console Info & Service Widgets

### LINKED ISSUE #339: [Feature Request] Unifi Controller Service Widget
**Is your feature request related to a service? Please describe.**
Add a service widget for a Unifi controller.

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
[Unifi controller API docs](https://ubntwiki.com/products/software/unifi-controller/start#controller_api)

### Discussed in https://github.com/benphelps/homepage/discussions/290

### PR DESCRIPTION
**Pull request by shamoon**
- Screen Shot 2022-10-05 at 9 35 18 PM
- Screen Shot 2022-10-08 at 5 48 03 PM

This PR adds service and info widgets for getting some basic info from a local UnifFi console. ~~It uses https://github.com/jens-maus/node-unifi for communicating~~ Edit: removed!. The API provides lots of data but I wanted to keep it simple and compact. It shows the system uptime, WAN status and the number of wireless + wired users.

This is my first time contributing to this project, certainly welcome all feedback and Im happy to adjust if anything is not to your liking.

Closes #290
Closes #339

(the wiki will need updating regarding the options if this is merged)

Edit:

Configs look like:
`settings.yaml`
```yaml
unifi_console:
    url: https://10.0.1.1:443
    username: user
    password: pass
```

`widgets.yaml` (info widget)
```yaml
- unifi_console:
```

`services.yaml` (service widget)
```yaml
- My First Group:
    - MyUDMPro:
        href: https://unifi.ui.com/dashboard
        description: My awesome Unifi Console
        icon: unifi.png
        widget:
            type: unifi
            url: https://10.0.1.1:443
            username: user
            password: pass
```

### CODE REVIEW

**Comment by shamoon** [comment]
Of course, no problem! I thought about writing my own since frankly we're only using a small portion of it. If there's a way for me to integrate that (perhaps a branch somewhere?) I'm happy to but if you'd prefer to modify this yourselves of course thats cool.

**Comment by JazzFisch** [comment]
@shamoon I'm working on incorporating my proxy change with your PR.  It's taking a little while though as it is requiring some changes to the way we store config data for info widgets.

**Comment by JazzFisch** [comment]
@shamoon I ended up finishing up sooner than I though, but I'm unable to push my changes to your PR branch.  Would you be willing to give me permissions to push my changes into your PR branch so you can view the changes prior to push an update?

**Comment by shamoon** [comment]
@JazzFisch of course, I tried inviting you, lmk if that worked

**Comment by JazzFisch** [comment]
@shamoon thanks!  Please have a look at the changes I made, and test them on your local environment.  I don't have a UDM Pro, so I can't test that code path, so if you do, please let me know that it works.

In order for your new info widget to work now, you update the following files.

In `settings.yaml` add the following block, uncommenting the version property if you have a UDM Pro.  
```yaml
unifi_console:
  #version: udm-pro
  url: https://unifi.home.local:8443
  username: username
  password: password
```

In `widgets.yaml` add the following line.  All settings are looked up server side out of the settings.yaml file, so you aren't required to put anything else in this file.
```yaml
- unifi_console:
```

**Comment by shamoon** [comment]
Ok! In the end perhaps its a good thing we can test both udm-pro (UDMP) and non-UDMP but it is funny we have to keep ping-ponging this. Hopefully I've made some small improvements and should still work for you too!

- UDMP _needs_ `Content-Type` header for login or it throws a 403, took me a while to figure that out 😅
- We can actually 'detect' if console is UDMP by pinging the base URL, if it returns the `x-csrf-token` header, its a UDMP. Then we can infer a lot from there e.g. port, "prefix" etc
- So, I changed the settings from `url` to `host` and removed the `type` parameter
- Also UDMP doesnt use `data.meta.rc` on successful login, I went with `data.login_time`
- You can still set a port in the settings though I dont know why a user would need to
- A few more tweaks but overall your proxy works great!

Welcome any changes / feedback, of course.

New settings.yaml looks like:
```
unifi_console:
    host: 10.0.1.1
    username: user
    password: pass
```

**Comment by shamoon** [comment]
Oh wait, the new proxy makes a service widget pretty easy too! Perhaps theres a way to make the component code a little more DRY but this was pretty straightforward, cool!

**Comment by JazzFisch** [comment]
@shamoon, the reason the proxy appears so multi-purpose is that I was almost done making my own service widget.  😁 
I'm glad you have a UDM Pro to test against, however your updated proxy approach requires additional requests each time simply to ascertain if the device you are talking to is a UDM or not.  I suppose we could use the memory cache to store that setting so we don't need to ever look it up while the container is running.  Additionally, I'm hesitant to change from the existing {url} token usage we have throughout homepage.

**Comment by shamoon** [comment]
Ha, oh didn't realize that but makes sense you were!

The extra call should just be the first time to determine if it's a UDMP but yea. In general my goal was to simplify things for the user.

Anyway, of course up to you guys, I'm happy to adjust.

**Comment by JazzFisch** [comment]
Let me see if I can come up with a way that does the UDM vs non-UDM check only one time.  😃

**Comment by shamoon** [comment]
> Let me see if I can come up with a way that does the UDM vs non-UDM check only one time. 😃

That sounds like a great idea, lmk if I can help. I was wondering about using caching somehow but you certainly know the guts of the code.

If there is a good solution we could consider using it for login too, currently we login only after a failed first attempt, as opposed to somehow storing the fact that we're logged in and thus potentially avoiding the initial fail. But yea, not sure about this.

**Comment by JazzFisch** [comment]
Interesting idea on using the cache to determine if you should pre-authenticate.  As this PR is getting a nudge long, maybe move that to a separate PR so that we can get all your Unifi goodness into main?  😄

I've made a couple of changes to align with our existing {url} token syntax and to cache the UDM check.  Have a look and let me know if it still works for you, and if you like it.

**Comment by shamoon** [comment]
Yea, fair enough, perma-PR 😅

Caching works great, nice!

I renamed the info widget too to keep things totally consistent. Also, I think we should keep the port detection, its part of the advantage of auto-detecting the udmp, otherwise we have to include in the docs that "for UDMP use :443, for non use :8443" when in fact we can infer this. I added that back for now.

_Note: I feel the same way about using `host` e.g. just the IP and no "https://" but I totally understand if you want to keep it consistent. I would submit that `host` is just another custom parameter like `username`, `weatherapi` or whatever and its safe to add the "https://" protocol ourselves so a user literally would just need to know the IP and login info, they dont need to know it has to be https. But again, I understand the aim for consistency. I didnt change this._

I'll leave these two points up to you once-and-for-all (again, I added port back but left `url`), otherwise Im happy with this and moreover, thanks for all the collaboration!

**Comment by JazzFisch** [comment]
> I renamed the info widget too to keep things totally consistent. 

They need to use two different names (for right now) I'm afraid as the settings come from two location.  One from settings.yaml and the other from services.yaml.  Can you go please go back to naming the info widget `unifi_console` and the service widget `unifi`?

> Also, I think we should keep the port detection, its part of the advantage of auto-detecting the udmp, otherwise we have to include in the docs that "for UDMP use :443, for non use :8443" when in fact we can infer this. I added that back for now.

We really can't infer port usage.  For instance, before I ran my Unifi controller inside of an LXC, I ran it in a docker container, and the controller was not running on 8443.

> _Note: I feel the same way about using `host` e.g. just the IP and no "https://" but I totally understand if you want to keep it consistent. I would submit that `host` is just another custom parameter like `username`, `weatherapi` or whatever and its safe to add the "https://" protocol ourselves so a user literally would just need to know the IP and login info, they dont need to know it has to be https. But again, I understand the aim for consistency. I didnt change this._

> I'll leave these two points up to you once-and-for-all (again, I added port back but left `url`), otherwise Im happy with this and moreover, thanks for all the collaboration!

Except URL is already a Uniform Resource Locator (😁) and contains all of that information without needing additional properties on our settings objects.  I don't think we need to tell anyone anything except point at the URL of your Unifi console.  Please change it back to using just URL with no port in both widget.js and proxy.js please.

**Comment by shamoon** [comment]
Ok no worries, I'll make the changes.

**Comment by shamoon** [comment]
Ok, all set =)

**Comment by shamoon** [comment]
Ps. with the auto-port detection I did previously have it so that you could still override the port in the settings =)

**Comment by JazzFisch** [comment]
Everything looked great shamoon, looks like there are just two last linter warnings to clear up and your all set.

> #52 6.443 ./src/widgets/unifi/component.jsx
#52 6.443 18:23  Error: Unexpected string concatenation.  prefer-template
#52 6.443 19:22  Error: Unexpected string concatenation.  prefer-template

**Comment by shamoon** [comment]
Ah my bad, all set!

**Comment by JazzFisch** [comment]
Nicely done!

**Comment by hunkyn** [comment]
Will this also work with 2FA?

**Comment by JazzFisch** [comment]
> Will this also work with 2FA?

You will want to use a built-in account to authenticate with as opposed to your UI account I believe.  That's how I was testing this and I have MFA turned on for my UI account.

**Comment by shamoon** [comment]
Yea I can’t tell if the API only works with local accounts but certainly the clients I looked through require that https://ubntwiki.com/products/software/unifi-controller/start . So yea, local only

**Comment by JazzFisch** [comment]
@shamoon I just updated the wiki with the info as outlined in your initial PR commit message.  Thanks again.

**Comment by shamoon** [comment]
Awesome thanks. Look forward to contributing more! (Less controversial next time 😆)

**Comment by hunkyn** [comment]
> Yea I can’t tell if the API only works with local accounts but certainly the clients I looked through require that https://ubntwiki.com/products/software/unifi-controller/start . So yea, local only

Ok thanks. I will use my local account if that is the case.

**Comment by hunkyn** [comment]
FYI, fields setting is not working correctly. uptime and wan work. lan and wlan are not working.

**Comment by JazzFisch** [comment]
> FYI, fields setting is not working correctly. uptime and wan work. lan and wlan are not working.

I see the issue.  I'll fix it soonish.

**Comment by JazzFisch** [comment]
@hunkyn should be fixed in #364.  Note, you'll want to re-read the wiki for correct fields though.  I had to rename them.

**Comment by dhmilton** [comment]
I have been having a read through this as I have both a UDMP and also a VM Based controller that I want to be able to use.
I am currently running docker build v0.4.18 (4ea2798, Oct 15, 2022) of homepage.
Whenever I try to use the widget againt the UDMP I am getting "API Error" and against the VM I get "TypeError: Cannot read properties of undefined (reading 'uptime')".
I am more interested in the UDMP so have been trying a lot more with that.
UDMP is running UniFi OS UDM Pro 1.12.30.
I have tried using http, https, FQDN, IP address.
I have created a local user with viewer permissions, and even briefly gave it admin rights in case that would work.
I am very happy to be a guinea pig here to test anything out.
I am looking to add it with the main services area of the screen rather than at the top in the widgets bar.
In the log I am seeing this:
error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://<ip_address>/api/stat/sites. Data: Not Found
I haven't installed anything extra or enabled any special settings on any of the Unifi Controllers other than creating the local user.

**Comment by dhmilton** [comment]
OK. Please don't ask me why, but I just tore down and redeployed the conatiner in a different stack as I wanted it to be on the same overlay network as some other containers, and now the UDMP is working.
Now I just need to try and see if I can get it working with the VM instances...

**Comment by hflatoey** [comment]
Hello :)

I am getting api error, think there might be a "." that shouldn't be there?

https://192.168.1.2:8443/api/stat/sites. <-- {"meta":{"rc":"error","msg":"api.err.NoSiteContext"},"data":[]}
[1:59 PM]
https://192.168.1.2:8443/api/stat/sites <-- {"meta":{"rc":"ok"} + a lot of info text

**Comment by dhmilton** [comment]
> Hello :)
> 
> I am getting api error, think there might be a "." that shouldn't be there?
> 
> https://192.168.1.2:8443/api/stat/sites. <-- {"meta":{"rc":"error","msg":"api.err.NoSiteContext"},"data":[]} [1:59 PM] https://192.168.1.2:8443/api/stat/sites <-- {"meta":{"rc":"ok"} + a lot of info text

Are you trying to connect to a Dream Machine Pro, Cloud key or virtual instance of the Unifi Controller?

**Comment by hflatoey** [comment]
> Are you trying to connect to a Dream Machine Pro, Cloud key or virtual instance of the Unifi Controller?

UniFi Controller
https://github.com/linuxserver/docker-unifi-controller

**Comment by shamoon** [comment]
@hflatoey perhaps #398 will solve the issue for you, Im not sure what you mean about an extra period, I dont think there is an extra period in this...

**Comment by hflatoey** [comment]
The "." is in the log "http://192.168.1.2:8443/api/stat/sites." I don't know why it doesn't say "https" because that's what I have in my config file and if I got to "https://192.168.1.2:8443/api/stat/sites" in my browser I get the API data.

But I will wait for the fix :)

**Comment by shamoon** [comment]
> The "." is in the log "http://192.168.1.2:8443/api/stat/sites." I don't know why it doesn't say "https" because that's what I have in my config file and if I got to "https://192.168.1.2:8443/api/stat/sites" in my browser I get the API data.
> 
> But I will wait for the fix :)

Using the API output you put in the other thread (and now deleted?) I verified the updated version works well with your controller, thanks

**Comment by Jimmy-SafeCash** [comment]
I receive the following error in a big red box:

`Something went wrong.
TypeError: Cannot read properties of undefined (reading 'uptime')`

I am using the controller in docker using linuxserver image. I am not using the default site - perhaps that is the issue? Could a site variable be added?

**Comment by Jimmy-SafeCash** [comment]
@shamoon any ideas ^^ - thanks.

**Comment by shamoon** [comment]
Please see https://github.com/benphelps/homepage/pull/398 , you need to use that version which is not in the last release yet, but is in `main`

**Comment by Jimmy-SafeCash** [comment]
@shamoon How can I specify a site? I have two sites on my controller.

**Comment by shamoon** [comment]
See #706

**Comment by VinneyUK** [comment]
Hi,
I need getting the error:

`API Error: Unknown error
URL: http://192.168.0.1/api/stat/sites
Raw Error:
{
    "code": "CERT_HAS_EXPIRED"
}`

If I use:
`           type: unifi
            url: https://192.168.0.1
            username: myuser
            password: mypass`

get then get the following issue error:

`API Error: HTTP Error 404
URL: https://192.168.0.1/api/stat/sites
Response Data:
Not Found`

Is this because I am using **UniFi OS UDM Pro 2.4.27 ??**

**Pull request merged**
