### PR TITLE
Fix: Support Synology DownloadStation v6 + v7

### LINKED ISSUE #768: [Bug] Downloadstation widget can't connect to my NAS
### Description

I've added a DownloadStation widget to my configuration to get informations on the download currently running on my NAS and I don't get any data. 

The logs display the following message : 

[2023-01-03T17:49:53.043Z] warn: <downloadstationProxyHandler> Unable to login.  Code: 103

Which seems to mean "Method not allowed" according to the DownloadStation API reference. 

My NAS is a DS216+ with 7.1.1-42962 Update 1 and up to date DownloadStation package.

On my developpement version (I'm working on a diskstation widget), I changed the authApi constant to 

const authApi = `{url}/webapi/entry.cgi?api=SYNO.API.Auth&version=3&method=login&account={username}&passwd={password}&session=DownloadStation&format=cookie`

and it seems to solve the problem.

But I'm not sure that it will not break compatibility with NAS running lower firmware versions. 

### Steps to reproduce

Activate a downloadstation widget : 
    - DS216:
        icon: synology.png
        href: url
        description: Synology DS216+
        widget:
          type: downloadstation
          url: url
          username: user
          password: verycomplicatedpassword

### homepage version

v0.5.9 (f6b1304, Dec 31, 2022)

### Installation method

Docker

### Configuration

_No response_

### Container Logs

_No response_

### Browser Logs

_No response_

### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

### PR DESCRIPTION
**Pull request by shamoon**
Co-Authored-By: Benoit SERRA <11260343+Oupsman@users.noreply.github.com>

Big thanks to @Oupsman for providing access to a v6 + v7 instance to test with. Oupsman if you wouldn't mind testing yourself to make sure, this works for me but I think because its a little slow because its so remote I occasionally see a little weirdness. This again uses the logic your code (hence co-author) just reorganized / refactored a bit.

Screen Shot 2023-01-03 at 3 44 14 PM

Closes #768

### CODE REVIEW

**Comment by Oupsman** [comment]
Everything is OK for me :+1:

**Comment by IIIdefconIII** [comment]
do you  have an example to use it for homepage? cant find the details somewhere

**Comment by shamoon** [comment]
Did you search the docs? https://gethomepage.dev/en/services/downloadstation/

**Comment by IIIdefconIII** [comment]
Ow it tought there was alsof a normal synology setups this is specifiek for download stations which I rfuse to use.x but thankss


Met vriendelijke groet,



Thomas van Dalen

E: ***@***.******@***.***>

T: +316 30 929 009<tel:+31630929009>

________________________________

**Pull request merged**
