### PR TITLE
Added search to quicklaunch

### PR DESCRIPTION
**Pull request by avdept**
Hey folks. So I've added this little part that adds option to search for item entered to quick launch panel. This is critical to those who needs google for something without moving hands away from keyboard to change focus on search input field. Please let me know if there needs something else to be added.

Screenshot 2023-01-30 at 10 19 20

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
Thanks for the PR. I've been meaning to add this.

We can't accept a hard-coded Google search here though, our users wouldn't really stand for that =)

This needs to use the configured search widget

**Comment by avdept** [comment]
> Thanks for the PR. I've been meaning to add this.
> 
> We can't accept a hard-coded Google search here though, our users wouldn't really stand for that =)
> 
> This needs to use the configured search widget

Yeah that makes sense. Just wanted to find out if this kind of change generally allowed. I will add more code to allow users to select preferable engine based on config.

**Comment by shamoon** [comment]
You can always open a discussion to discuss

Just to clarify, I don’t mean a separate configuration for this, I mean whatever search provider is configured as a widget

we can, of course, help with that if you’d like

**Comment by JazzFisch** [comment]
It would be nice if there was a way to not have the internet search provider checked when doing a quick search.

**Comment by shamoon** [comment]
Take a look, I updated this to:

- Use the configured search provider
- Make quick launch internet search hideable (`hideInternetSearch: true`)
- Also changed what the title shows
- Also shows type `Search` not service

Screenshot 2023-01-30 at 11 34 39 PM
Screenshot 2023-01-30 at 11 34 45 PM

**Comment by avdept** [comment]
Great work! Was in middle of doing it myself, but glad you made it first!

**Comment by avdept** [comment]
Also I've noticed its not going to work with custom search provider, only with default

**Comment by shamoon** [comment]
> Great work! Was in middle of doing it myself, but glad you made it first!

Sorry about that mate!

> Also I've noticed its not going to work with custom search provider, only with default

Ah, good point. Gotta test this.

**Comment by shamoon** [comment]
Ok custom should be sorted too, thanks for pointing that out

**Pull request merged**
