### PR TITLE
Custom JS and CSS

### PR DESCRIPTION
**Pull request by TheRolfFR**
## Context

Hello @benphelps,
I have been experiencing with homepage, and the idea looks very promising.
I wanted some custom CSS, and even though the intent was not successful at first #904, I really wanted to give it a shot.

## Proposed changes
First, I started to add classes to the different information widgets. It is not easy as the structure itself involves modifying every single component. It's indeed very time consuming and __I have never used Next.js__ (I used many frameworks, but not this one).
However I think we could figure out something more general to make it faster. **Some help would be very appreciated**.

The use [CSS modules](https://nextjs.org/docs/app/building-your-application/styling/css-modules)  and [@apply directive](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply) would also help reduce visual clutter and abusive use of the classNames module.

As you will see, it includes many new classes, generally starting with ``information-widget-`` to make it clear it's an information widget. A little long, but it can be changed as desired.
I also added several ids for the information widgets container, the right container part and the elements at the bottom of the page.

To stylize, I added 2 files into the skeleton folder (maybe they could be optional, what do you think?).
Then I created and API endpoint to read from the config folder any file basically.
I used SWR to make a new component that refreshes dynamically the file content changes (useful when experimenting styles).
I included new style and script html tags into the index page (I don't know where to place, it was sometimes not rendered)

## Service IDs 
I added the possibility to add an ID to the service HTML element, by setting the ``id`` attribute of the described service.
You can then use it to style or add JS if you want.

## Result possible
I use it to move the resource widget label, make the logo container grow, and adjust the spacing and alignment in general:

*Before*
image
*After*
image

## Document PR when solutions established
As this framework and ideas very subject to change, I will make a PR 

## Issues and discussions related
Please modify this but at least #139 

## Type of change

- [no] New service widget
- [no] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [no] Other (please explain)

## Checklist:

- [x]  If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 

- [no] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [n/a] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
This is an interesting approach, thanks for the PR. Im guessing youve tested this in a docker image and it works? I wont be able to test until later but looking at it, the only downside of the approach I can imagine would be a delay in applying the custom styles but perhaps thats minor / not even noticeable.

I dont love all of the custom classes, it feels a bit anti-tailwind but obviously I see the purpose. And you havent added them for service widgets?

The requested changes are all minor things, regardless the PR is well done but Im curious what phelps things.

**Comment by TheRolfFR** [comment]
> I dont love all of the custom classes (also inconsistent use of id vs class e.g. `information-widget-glances` should probably be an id), it feels a bit anti-tailwind but obviously I see the purpose. And you havent added them for service widgets?

I added a paragraph in the issue description and personnally I use multiple Glances instances

>  I can imagine would be a delay in applying the custom styles but perhaps thats minor / not even noticeable.

Default refresh time for the file content component is 1500ms, but it's an attribute that can be changed as desired

**Comment by shamoon** [comment]
Yea I realized the multiples thing for classes vs ids, duh thanks

**Review by shamoon — APPROVED** [review]
Again, this is really clever and I think people will love it. Thanks for the PR

**Comment by shamoon** [comment]
Sorry I did make one actual change which is instead of refreshing and wasting network calls every 1.5s I added these files to the hash which means:

- homepage will auto-detect changes
- the [empty] files will get created automatically

Let me know if you have any concerns with that

**Comment by TheRolfFR** [comment]
Yes, sure, please do. You know the tech and codebase better.
I didn't want to touch others API routes because I didn't want to break anything ^^
Thanks for the doc by the way!

I added preloading to the pages to get them earlier, tell me what you think

**Comment by shamoon** [comment]
Cool yea preload a good idea

**Pull request merged**
