### PR TITLE
Add 5th column for 2xl screens

### LINKED ISSUE #987: [Feature Request] Add a 5th column for ultra wide screens
### Description

Is it possible to add a 5fth catagorie colum? would be lovely on a ultra wide screen

image
### Other

i know there is a css trick, but that shows them all together on a single line and isnt persisstant.
is it possible to make the .flex-wrap side larger? with flex.wrap disabled, its make it too huge:
image
image

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

For [2xl e.g. > 1536px](https://tailwindcss.com/docs/screens)

Closes #987 

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by IIIdefconIII** [comment]
cool, is there a documentation how to set this up? cant find it, anyway thanks for adding this, not figering out how to apply it

**Comment by IIIdefconIII** [comment]
Yeah but i mean 5 catagories next to each other


Met vriendelijke groet,



Thomas van Dalen

E: ***@***.******@***.***>

T: +316 30 929 009<tel:+31630929009>

________________________________

**Comment by spezzuti** [comment]
So I noticed this change because it affected my layout, moving a column that was the 1 of 4 columns in the next row down, but is now the 5 column in the row above. Can this 5th column be changed? Sites/Streaming has moved up, becoming the 5th column.
Screenshot 2023-04-08 010545

**Comment by shamoon** [comment]
Yea Im not happy with this, Im going to move it behind a 'flag' `fiveColumns: true`.

**Comment by spezzuti** [comment]
Perfect! Def like the idea, but the flag will be helpful for these random situations. Appreciate the quick response

**Comment by IIIdefconIII** [comment]
> 

Thank man that worked perfectly!
image

**Comment by fate8383** [comment]
Five Columns

You can add a fifth column (when style: columns which is default) by adding:
fiveColumns: true

I keep adding in the settings but I cannot get the 5th column? any specific place to add it?

theme: dark

color: stone

headerStyle: clean

layout:
  1:
    icon: ubuntu.png
  2:
    icon: raspberrypi.png
  3:
    icon: raspberrypi.png
  4:
    icon: debian.png
  5:
    icon: google-home.png

fiveColumns: true

language: en

target: _blank

**Comment by IIIdefconIII** [comment]
>did YouTube put it on setting.yaml?

 Five Columns
> 
> You can add a fifth column (when style: columns which is default) by adding:
> fiveColumns: true
> 
> I keep adding in the settings but I cannot get the 5th column? any specific place to add it?
> 
> theme: dark
> 
> color: stone
> 
> headerStyle: clean
> 
> layout:
>   1:
>     icon: ubuntu.png
>   2:
>     icon: raspberrypi.png
>   3:
>     icon: raspberrypi.png
>   4:
>     icon: debian.png
>   5:
>     icon: google-home.png
> 
> fiveColumns: true
> 
> language: en
> 
> target: _blank
> 
> 
> 
> also seeing error in the logs:
> 
> [2023-04-08T21:53:43.580Z] warn: Failed to update prerender cache for /en [Error: EACCES: permission denied, open '/app/.next/server/pages/en.html'] {
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'open',
>   path: '/app/.next/server/pages/en.html'
> }
> 
> not sure if related.

**Comment by fate8383** [comment]
> did You put it on setting.yaml?

yes, above pasted the config fully. I noticed I have to lower my zoom to 100% or less to get the 5th column, a version before it was default showing the 5th column

**Comment by IIIdefconIII** [comment]
> > did You put it on setting.yaml?
> 
> yes, above pasted the config fully. I noticed I have to lower my zoom to 100% or less to get the 5th column, a version before it was default showing the 5th column

that odd even when i zoom to 175% its showing 5 columns
you previous post its better to use the ``` ``` tags to keep the post clean

**Comment by fate8383** [comment]
> did You put it on setting.yaml?
> 
> > yes, above pasted the config fully. I noticed I have to lower my zoom to 100% or less to get the 5th column, a version before it was default showing the 5th column
> 
> thats odd even when i zoom to 175% its showing 5 columns

`---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

background: /images/blackback.png

#backgroundOpacity: 100

theme: dark

color: stone

headerStyle: clean

layout:
  1:
    icon: ubuntu.png
    style: columns
  2:
    icon: raspberrypi.png
    style: columns
  3:
    icon: raspberrypi.png
    style: columns
  4:
    icon: debian.png
    style: columns
  5:
    icon: google-home.png
    style: columns

fiveColumns: true

language: en

target: _blank`

**Comment by fate8383** [comment]
> did You put it on setting.yaml?
> 
> > yes, above pasted the config fully. I noticed I have to lower my zoom to 100% or less to get the 5th column, a version before it was default showing the 5th column
> 
> thats odd even when i zoom to 175% its showing 5 columns

sorry I cannot figure out the tagging... could you maybe share yours just the part where you added fiveColumns: true ?

**Pull request merged**
