### PR TITLE
Add Readarr and SABnzbd widgets

### PR DESCRIPTION
**Pull request by JazzFisch**
Hi Ben,
Hopefully this is an appropriate way of submitting new widgets.  I wasn't sure what to do about the translations, and wasn't sure if I should update the README.md as well.

### CODE REVIEW

**Comment by benphelps** [comment]
For translations, only apply the new keys to languages you can natively or fluently translate, Weblate will handle updates to other files (and marking them as "Needs Translation") automatically.

Other than that, everything looks good.

**Comment by JazzFisch** [comment]
> For translations, only apply the new keys to languages you can natively or fluently translate, Weblate will handle updates to other files (and marking them as "Needs Translation") automatically.
> 
> Other than that, everything looks good.

To make sure I understand, remove the non-English translations?

**Comment by JazzFisch** [comment]
Oh, and should I link this against issue #103?

**Comment by benphelps** [comment]
> > For translations, only apply the new keys to languages you can natively or fluently translate, Weblate will handle updates to other files (and marking them as "Needs Translation") automatically.
> > Other than that, everything looks good.
> 
> To make sure I understand, remove the non-English translations?

Correct.

**Comment by benphelps** [comment]
> Oh, and should I link this against issue #103?

Yep :)

**Pull request merged**
