### PR TITLE
Change TrueNAS to use API key

### PR DESCRIPTION
**Pull request by jhollowe**
Using an API key is better than username/password and it is easy to generate an API key in TrueNAS.

Documentation updates in https://github.com/benphelps/homepage-docs/pull/18

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
Hmm, but this is a breaking change for literally all users with this widget setup. I don’t use Truenas myself but seems hard to justify unless we know that most folks agree. 

So yea, without a clear mandate to change I think this would need to support both, which can be done

**Comment by shamoon** [comment]
I have fixed this but I cant push to your fork. Can you either grant me access or I can recreate the PR, up to you.

**Comment by jhollowe** [comment]
You should be able to push to it now.

**Comment by shamoon** [comment]
Sweet thanks, take a look and let me know, this should support both

Screen Shot 2023-01-07 at 10 10 00 AM

**Review by jhollowe — COMMENTED** [review]
Looks good!

**Comment by shamoon** [comment]
Awesome thanks

**Pull request merged**
