### PR TITLE
MDI - Icons as YAML Setting

### PR DESCRIPTION
**Pull request by dieideeistgut**
Heya,

this is my addition of MDI icons to homepage. I am no expert in this field - feel free to decline. Maybe this serves ans an idea. MDI-Syntax i use is:

```
- Stockholm:
    - ShyNet:
        description: ShyNet Tracking
        icon: 'mdi mdi-chart-timeline-variant-shimmer'
```

### CODE REVIEW

**Comment by shamoon** [comment]
I think react-icons has md icons? https://react-icons.github.io/react-icons/icons?name=md

**Comment by dieideeistgut** [comment]
Didn't know that. What would be a decent syntax for implementing those via `icon` ?

**Comment by benphelps** [comment]
Including the MDI font and CSS is too heavy, we use React Icons as that allows tree shaking so we only include the icons being used in the final bundled application.

I played around with this a bit and got something working that fetches the SVG icons from the jsdeliver CDN instead.

Since we can't style SVGs that are inside of an  tag, we have to resort to some more creative alternatives.  This is using the logo gradient stops to color a div and then using the SVG as a mask.

Screenshot 2022-10-11 at 2 19 17 PM
Screenshot 2022-10-11 at 2 18 50 PM
Screenshot 2022-10-11 at 2 18 43 PM
Screenshot 2022-10-11 at 2 18 36 PM
Screenshot 2022-10-11 at 2 18 21 PM

**Comment by dieideeistgut** [comment]
Looks nice, works sweetly. Many thanks for this.

**Pull request closed without merging**
