### PR TITLE
Add Azure DevOps

### PR DESCRIPTION
**Pull request by Nizzan943**
## Proposed change
add new features to Azure Pipelines and merged together as Azure DevOps.

use to monitor pull requests status in specific repository.

image

Closes #1693 

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [X] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: [127](https://github.com/benphelps/homepage-docs/pull/127)
- [X] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [X] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by Nizzan943** [comment]
The only con in this way is we fetching widget 2 api requests and not 1.
Because of useWidgetAPI hook should be before ```if(azureType)```. looking for advice

**Review by shamoon — CHANGES_REQUESTED** [review]
This looks good for the most part but I think we need to shorten "My Approved Not Completed" text, "Incomplete"? "Approved"?

Also where does the 10 reviewers thing come from?

**Comment by Nizzan943** [comment]
> This looks good for the most part but I think we need to shorten "My Approved Not Completed" text, "Incomplete"? "Approved"?
> 
> Also where does the 10 reviewers thing come from?

Done.

I know only 3 peoples that hit up-vote, we are all using homepage and love with the product.

**Review by shamoon — CHANGES_REQUESTED** [review]
So a couple things:

1. Even though they are kinda two widgets you can merge some things, for example the error display should be one block.
2. Currently this doesnt allow showing both types of the widget. Do you want to consider supporting that? As I mentioned in the other PR if you can keep it under 4 total blocks then you could conceivably have both at the same time.
3. If not then there is a way to actually limit the API calls, you would change the second parameter to `useWidgetAPI` i.e. `count endpoint = (type === "Pipeline") ? "pipeline" : "pr"` and then call it once.

But again, I think it would be cooler to have them both work at the same time, users can disable any that they dont want with the `fields` option

**Comment by Nizzan943** [comment]
Hey,
I dropped `BuildId` Block.
I tried to make both functionalities work together, but unfortunately, it seems to be not convenient.
If the user wants to have both functionalities, it works fine because the widget has all the relevant fields to fetch both API requests.
but let's say if user wants only a pipeline, so he wants to use this configuration:
```
          type: azuredevops
          fields: ["result", "status"]
          organization: some-organization
          project: some-project
          userEmail:  some@email.com
          branchName: some-branch-name
          definitionId: some-id
          key: keykeykey
```
The issue is that we are missing branchName field (from PR functionality) which leads to the widget fetching this endpoint:
`..../_apis/git/repositories//pullrequests` and gets 404.
the opposite way is not an issue, because `builds/Build` endpoint will just give back the last pipeline that ran, the user can filter it with `fields` parameter.

Regardless of what I wrote up here, I have weird behavior after merging widgets that make widgets crazy, nothing seems to be broken. When this situation happens to me in the video, I used all fields for each widget to prevent 404 from PR endpoint.
so I used, but with real data:
```
          type: azuredevops
          fields: ["result", "status"]
          organization: some-organization
          project: some-project
          userEmail:  some@email.com
          branchName: some-branch-name
          definitionId: some-id
          repositoryId: some-repository          
          key: keykeykey
```
https://github.com/benphelps/homepage/assets/59150911/0fa82d30-7fa2-412f-b100-6905fdaf32c8

**Comment by shamoon** [comment]
If you push the changes you have I can try to help out tomorrow

**Comment by Nizzan943** [comment]
> If you push the changes you have I can try to help out tomorrow

yeah sorry I did it in 4am last night :D
pushed

**Comment by shamoon** [comment]
Ok take a look at the last commit, it should handle this stuff a bit better.

If `branchName` & `userEmail` aren't supplied we can assume user doesnt want that so just hide the fields, ignore any api errors for PR. Arguably we could have a similar logic the other way around, we can still add that but I think as you mentioned it won't error and they can just hide the field.

Play with it a bit and see if you note any issues, we'll squash the commits and resolve the merge errors once its ready.

**Comment by Nizzan943** [comment]
I did and it seems good to me.
I accidently told you the `branchName` is the issue but it was repositoryId, sorry it was 4AM :)

2 things:
1. I dont like the idea we are fetching api request everytime twice when it not needed, how it can be solved?
2. using fields for unknown reason crashing widget.
image
image
Am I use it wrong?
both widgets in the picture has same settings but `Repo 1` have also ```fields: ["totalPrs", "myPrs","approved"]```

**Comment by shamoon** [comment]
should be sorted, lmk

Screenshot 2023-07-26 at 8 33 58 PM
Screenshot 2023-07-26 at 8 34 06 PM

**Review by shamoon — APPROVED** [review]

**Pull request merged**
