### PR TITLE
Add support for QNAP instances with multiple volumes

### PR DESCRIPTION
**Pull request by theshaun**
## Proposed change

I noted an issue in my environment when adding additional volumes. Also picked up by another user who reached out directly. Causing the following error:
image

This pull request adds support for cases where more than one volume is on a qnap. Instead of erroring out it now collates the total volume space correctly:
image

Additionally I have added support for defining a volume to be tracked (I will follow this with an update to the documentation.

If volume is defined in config with the volume name from QNAP, it will show as:
image

If an incorrect volume is typed, instead of erroring it will return as follows:
image

I realise this adds a bit more complexity to the component, can adjust if need be.

Cheers again for this great project.

Closes # (issue)

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [ ] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by shamoon** [comment]
Can you post example api output for multiple volumes?

**Comment by shamoon** [comment]
And the reason you keep getting other commits is youre using a stale branch, you need to create the branch from `main` next time

**Comment by theshaun** [comment]
Thanks @shamoon, will note that for next time.

Cheers for adding that missing translation, I should have ensured to add one for the word invalid.

API output from the volumeStatsData with multiple volumes is as below:
````yaml
{
    "_declaration": {
        "_attributes": {
            "version": "1.0",
            "encoding": "UTF-8"
        }
    },
    "QDocRoot": {
        "_attributes": {
            "version": "1.0"
        },
        "authPassed": {
            "_cdata": "1"
        },
        "model": {
            "modelName": {
                "_cdata": "TS-X73A"
            },
            "internalModelName": {
                "_cdata": "TS-X73"
            },
            "platform": {
                "_cdata": "TS-NASX86"
            },
            "platform_ex": {
                "_cdata": "X86_SUMMITRIDGE"
            },
            "customModelName": {},
            "displayModelName": {
                "_cdata": "TS-873A"
            },
            "sas_model": {
                "_cdata": "0"
            },
            "storage_v2": {
                "_text": "1"
            },
            "encryptfsSupported": {
                "_cdata": "1"
            },
            "is_zfs": {
                "_cdata": "0"
            },
            "node": {},
            "dual_node": {}
        },
        "firmware": {
            "name": {
                "_cdata": "QTS"
            },
            "version": {
                "_cdata": "5.0.1"
            },
            "number": {
                "_cdata": "2376"
            },
            "build": {
                "_cdata": "20230421"
            },
            "patch": {
                "_cdata": "0"
            },
            "buildTime": {
                "_cdata": "2023/04/21"
            }
        },
        "rfs_bits": {
            "_cdata": "64"
        },
        "specVersion": {
            "_cdata": "1.0"
        },
        "hostname": {
            "_cdata": "<<REMOVED>>"
        },
        "DemoSiteSuppurt": {
            "_cdata": "no"
        },
        "customLogo": {
            "customFrontLogo": {},
            "customLoginLogo": {}
        },
        "volumeList": {
            "volume": [
                {
                    "volumeStat": {
                        "_cdata": "mirror"
                    },
                    "volumeDisks": {
                        "_cdata": " 1,2"
                    },
                    "volumeStatus": {
                        "_cdata": "0"
                    },
                    "Progress": {
                        "_cdata": "100"
                    },
                    "volumeType": {
                        "_cdata": "1"
                    },
                    "volumeValue": {
                        "_cdata": "1"
                    },
                    "freeSize": {
                        "_cdata": "11894"
                    },
                    "fstype": {
                        "_cdata": "9"
                    },
                    "volumeLabel": {
                        "_cdata": "DataVol1"
                    },
                    "FSRVP_support": {
                        "_cdata": "0"
                    },
                    "edge_cache_support": {
                        "_cdata": "0"
                    },
                    "edge_cache_type": {
                        "_cdata": "-1"
                    },
                    "FolderCounter": {
                        "_cdata": "15"
                    },
                    "is_legacy_volume": {
                        "_cdata": "0"
                    },
                    "is_default_volume": {
                        "_cdata": "1"
                    },
                    "pool_vjbod": {
                        "_cdata": "0"
                    },
                    "encryptfs_bool": {
                        "_cdata": "0"
                    },
                    "encryptfs_active_bool": {
                        "_cdata": "0"
                    },
                    "encryptfs_key_flag": {
                        "_cdata": "N"
                    }
                },
                {
                    "volumeStat": {
                        "_cdata": "raid5"
                    },
                    "volumeDisks": {
                        "_cdata": " 7,8,9,10"
                    },
                    "volumeStatus": {
                        "_cdata": "0"
                    },
                    "Progress": {
                        "_cdata": "100"
                    },
                    "volumeType": {
                        "_cdata": "1"
                    },
                    "volumeValue": {
                        "_cdata": "2"
                    },
                    "freeSize": {
                        "_cdata": "3486"
                    },
                    "fstype": {
                        "_cdata": "9"
                    },
                    "volumeLabel": {
                        "_cdata": "DataVolTest"
                    },
                    "FSRVP_support": {
                        "_cdata": "0"
                    },
                    "edge_cache_support": {
                        "_cdata": "0"
                    },
                    "edge_cache_type": {
                        "_cdata": "-1"
                    },
                    "FolderCounter": {
                        "_cdata": "0"
                    },
                    "is_legacy_volume": {
                        "_cdata": "0"
                    },
                    "is_default_volume": {
                        "_cdata": "0"
                    },
                    "pool_vjbod": {
                        "_cdata": "0"
                    },
                    "encryptfs_bool": {
                        "_cdata": "0"
                    },
                    "encryptfs_active_bool": {
                        "_cdata": "0"
                    },
                    "encryptfs_key_flag": {
                        "_cdata": "N"
                    }
                }
            ]
        },
        "volumeUseList": {
            "volumeUse": [
                {
                    "volumeValue": {
                        "_cdata": "1"
                    },
                    "total_size": {
                        "_cdata": "19633542168576"
                    },
                    "free_size": {
                        "_cdata": "12797236248576"
                    },
                    "folder_element": [
                        {
                            "sharename": {
                                "_cdata": "Public"
                            },
                            "used_size": {
                                "_cdata": "33579008"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "Multimedia"
                            },
                            "used_size": {
                                "_cdata": "4636968857600"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "Recordings"
                            },
                            "used_size": {
                                "_cdata": "24576"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "Container"
                            },
                            "used_size": {
                                "_cdata": "11556745216"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "shares"
                            },
                            "used_size": {
                                "_cdata": "4096"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "QVRProDB"
                            },
                            "used_size": {
                                "_cdata": "809828352"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "QVRProRecording"
                            },
                            "used_size": {
                                "_cdata": "16384"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "QVRProAutoSnap"
                            },
                            "used_size": {
                                "_cdata": "16384"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "QVRProAppData"
                            },
                            "used_size": {
                                "_cdata": "1048576"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "QVRProSpace_DataVol1"
                            },
                            "used_size": {
                                "_cdata": "179651620864"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "QuObjects_Storage"
                            },
                            "used_size": {
                                "_cdata": "32768"
                            }
                        },
                        {
                            "sharename": {
                                "_cdata": "System Reserved"
                            },
                            "used_size": {
                                "_cdata": "80526528512"
                            },
                            "type": {
                                "_cdata": "system"
                            }
                        }
                    ],
                    "others_size": {
                        "_cdata": "6758994370560"
                    },
                    "found_quota": {
                        "_cdata": "0"
                    }
                },
                {
                    "volumeValue": {
                        "_cdata": "2"
                    },
                    "total_size": {
                        "_cdata": "3750808633344"
                    },
                    "free_size": {
                        "_cdata": "3750716317696"
                    },
                    "folder_element": [
                        {},
                        {
                            "sharename": {
                                "_cdata": "System Reserved"
                            },
                            "used_size": {
                                "_cdata": "32768"
                            },
                            "type": {
                                "_cdata": "system"
                            }
                        }
                    ],
                    "found_quota": {
                        "_cdata": "0"
                    }
                }
            ]
        }
    }
}
````

**Comment by theshaun** [comment]
Amusingly I note that even the qnap API misses some important info (unrelated to our needs here). It marks the first volume as a mirror, when its a raid5 + tiered mirrored nvme. Interesting. I might raise that with QNAP

**Comment by shamoon** [comment]
Great thanks

**Comment by shamoon** [comment]
(when you have a sec dont forget the docs update)

**Comment by theshaun** [comment]
Cheers, have added patch for doco change: https://github.com/benphelps/homepage-docs/pull/103

**Pull request merged**
