### PR TITLE
Feature: calendar widget

### PR DESCRIPTION
**Pull request by denispapec**
## Proposed change

This PR implements calendar widget, with optional integrations to show events from supported widgets. This PR has support for radarr, sonarr, lidarr and readarr.

Screenshot_20230924_171006

Closes #1243
Closes #1015
Closes #1200

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (please explain)

## Checklist:

- [x] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: https://github.com/benphelps/homepage-docs/pull/161
- [x] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [x] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by ozdeadmeat** [comment]
Holy crap this is awesome, when is this coming to the main branch?

**Review by shamoon — APPROVED** [review]
This is great overall and really 'just works' out of the box.

I hit a couple tiny bugs at first so fixed those and I made small changes, all individual commits so you can see (we'll squash & merge this anyway).

Only notable change is making it scale width on larger sizes and I made the 'includeSeries' and 'includeAuthor' options default to true, my feeling is it provides a better experience and users can always turn that off if they want.

Great work, let me know if you have any concerns re the above

Screenshot 2023-09-27 at 10 06 20 PM
Screenshot 2023-09-27 at 9 08 39 PM
Screenshot 2023-09-27 at 9 08 10 PM

**Comment by shamoon** [comment]
Oh yea, I also changed `integration` to `integrations` in the widget config =)

**Comment by shamoon** [comment]
Sorry, what did you mean by your last comment? You want me to revert your last commit? https://github.com/benphelps/homepage/pull/2077/commits/14e9ce5aba829cd162aa932f6e410d19634f5870

**Comment by shamoon** [comment]
(because `firstDayInWeek` works fine for me in testing)

**Comment by denispapec** [comment]
Sorry, I was in a rush this morning.
After I've noticed that I've pushed config that causes the issue, I wanted to mention that in case you want to merge the widget into main branch, you can revert the last commit without the issue and freely merge. 
Btw. issue seems to be that when `sunday` is `firstDayInWeek`, it doesn't show me first week at all in this month, it show Sunday 3rd as first day. I'll have a look this evening and come with a fix or revert :)

**Comment by shamoon** [comment]
Ah yea, I see.

Honestly, Im ok without that anyway, lets merge it 💪

**Comment by Shagon94** [comment]
@denispapec would it be possible to implement a button that will go to the current date? For example, by clicking on the "Calendar" we could go back to the current date. This is useful once you go back or forward a few months and want to go back. Workaround for this is to just refresh the page.

image

**Comment by Nonoss117** [comment]
@denispapec , I posted a new feature request here: https://github.com/benphelps/homepage/discussions/2086

Thanks for this awesome widget

**Comment by Ramss3s** [comment]
how can i put the rest of links in right? 
Screenshot 2023-09-30 172945

**Comment by shamoon** [comment]
Commenting on closed PRs is not the way to make a feature or get help.

to answer your q, those links in the screenshot are just other services in a column next to the calendar

**Pull request merged**
