### PR TITLE
Add Pyload widget

### PR DESCRIPTION
**Pull request by stuffinator**
Adds a simple widget for monitoring [Pyload](https://github.com/pyload/pyload/) downloads.

image

possible fields:
- speed
- active
- queue
- total

example config:
```yaml
- Pyload:
        icon: /icons/pyload.png
        href: http://home:8668/
        description: Download Manager
        container: pyload
        widget:
            type: pyload
            url: http://home:8668
            username: secure_monitor
            password: super!secret
```
The pyload user in question needs at least "LIST" permissions.
Empty passwords are also supported. So you can create a monitoring user with only "LIST" permissions and no password.

This would look like this in the config:
```yaml
widget:
    type: pyload
    url: http://home:8668
    username: monitor
```

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for the PR, we’ll take a look. In the meantime please revert the changes to the de language file (and force-push to this branch), the only one you should directly edit is en

**Comment by stuffinator** [comment]
> In the meantime please revert the changes to the de language file

done

**Comment by shamoon** [comment]
Thanks! Again haven’t tested yet but looking at this (on my phone) looks like it’ll logon every time, is it possible to cache the login for some time and thus potentially avoid the login call? Many APIs will return an expiration or something like that, not sure about pyload.

(also in general I’d be curious to know how much interest there is for this in the community but hard to know that)

**Comment by Nonoss117** [comment]
> (also in general I’d be curious to know how much interest there is for this in the community but hard to know that)

I'm interested :-)

**Comment by shamoon** [comment]
Hey, please take a look at my changes, of course feel free to revert / change or let me know if you have concerns.

This now caches the sessionId so may not need to login. Since Im not sure when (if?) that expires we just try with the sessionId, catch a failure and try again. Also just refactored a bit to make it a bit more D.R.Y. =)

**Comment by shamoon** [comment]
Oh wait, sorry this is also not properly using the proxy, need to fix that.

**Comment by shamoon** [comment]
Ok thats sorted, please see we should be using `httpProxy` not `fetch` which is sent from the browser

**Comment by stuffinator** [comment]
I was just lazy, copied the npm proxy (which uses fetch) and adjusted it to my needs :smile: 

Anyway I don't have much time today, so I will have a look at your changes tomorrow and see if it works in my environment.

**Comment by shamoon** [comment]
Ha, yea I figured. That’s what led me to notice all this :) eg #499

**Comment by stuffinator** [comment]
Ok I made some changes, cause it didn't work with empty passwords. Also I had a look at your contribution guide lines and realized some of the stuff didn't align with the airbnb style guide, so I changed that as well.

Everything seems to work now. Thanks for your assistance with parts of the code. I totally forgot about the caching of the login :smile:

**Comment by shamoon** [comment]
👍

We dont enforce the style guide, should probably setup a precommit or something for that.

Thanks for the PR.

**Pull request merged**
