### PR TITLE
Add user and restart options to docker-compose

### PR DESCRIPTION
**Pull request by joaoportela**
Add user:group 1000:1000 to the docker compose, to match host user. Restart container unless stopped.

## Proposed change

Change the default user. When mounting files from the host, it's better to match the host user:group. Usually that is 1000:1000, which makes it a good default.

When deploying this container, the user usually want to keep the container running persistently, hence the restart unless stopped.

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (please explain)

Change example docker-compose in README.

## Checklist:

- [ ] If adding a service widget or a change that requires it, I have added a corresponding PR to the [documentation](https://github.com/benphelps/homepage-docs) here: 
- [ ] If adding a new widget I have reviewed the [guidelines](https://gethomepage.dev/en/more/development/#service-widget-guidelines).
- [ ] If applicable, I have checked that all tests pass with e.g. `pnpm lint`.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

### CODE REVIEW

**Comment by joaoportela** [comment]
I don't know if this affects the `/var/run/docker.sock:ro` mount, because I'm not using it.

**Comment by shamoon** [comment]
I dont think this belongs in our compose, it is not always the case and I think we're asking for a lot of issues from people having problems

This will also break mounting the docker socket

I suppose if you feel strongly about the restart option we can include that

**Comment by joaoportela** [comment]
> This will also break mounting the docker socket

I guess that's a deal breaker then... 😅 

I'll open one with the restart. I think it's pretty standard usage.

**Comment by shamoon** [comment]
Actually, you could just comment out the `user` line with a (brief) explanation. That way users can think about it

**Pull request merged**
